import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.user.createMany({
    data: [
      { email: "jana@zare.cz", displayName: "Jana Nováková", role: "admin" },
      { email: "ucetni@zare.cz", displayName: "Účetní", role: "accountant" },
      { email: "1beh@zare.cz", displayName: "1beh", role: "admin" },
    ],
    skipDuplicates: true,
  });

  await prisma.categoryTemplate.createMany({
    data: [
      { name: "potraviny", description: "Necessary food for a multi-day event: ingredients for cooking, bread, groceries, snacks that could reasonably be part of a meal plan. For short events, most food should usually be classified as občerstvení instead, since food is often not necessary." },
      { name: "občerstvení", description: "Extra food or drinks not part of the meal plan: sweets, popcorn, ice cream, food from stalls or restaurants, refreshments. For short events, most food typically belongs here rather than in potraviny." },
      { name: "materiál program", description: "Supplies used for activities, games, crafts, and programme preparation." },
      { name: "materiál provoz LT", description: "Operational camp materials: cleaning supplies, maintenance supplies, equipment needed to run the camp." },
      { name: "doprava účastníků na akci a zpět", description: "Transport of participants to and from the event." },
      { name: "doprava během tábora - výlety", description: "Transport during the camp, including trips and excursions." },
      { name: "vstupné", description: "Tickets, entrance fees, attractions." },
      { name: "odměny", description: "Rewards, prizes, small gifts." },
      { name: "autoprovoz", description: "Car operation costs: fuel, parking, car-related expenses." },
      { name: "stravování", description: "Catering, prepared meals, meal services." },
      { name: "ostatní služby", description: "Other services." },
      { name: "spotřeba EE, plynu a vody ( paušál PS )", description: "Electricity, gas, water — utility lump sum." },
      { name: "jiné výdaje", description: "Use when an expense is valid but does not fit another category, or when no allowed category is suitable." },
      { name: "rezerva", description: "Use only if the receipt clearly relates to a reserve or contingency fund." },
    ],
    skipDuplicates: true,
  });

  await prisma.translation.createMany({
    data: [
      { key: "common.loading", cs: "Načítání...", en: "Loading..." },
      { key: "common.delete", cs: "Smazat", en: "Delete" },
      { key: "common.edit", cs: "Upravit", en: "Edit" },
      { key: "common.save", cs: "Uložit", en: "Save" },
      { key: "common.cancel", cs: "Zrušit", en: "Cancel" },
      { key: "common.add", cs: "Přidat", en: "Add" },
      { key: "common.name", cs: "Jméno", en: "Name" },
      { key: "common.status", cs: "Stav", en: "Status" },
      { key: "common.statusActive", cs: "Aktivní", en: "Active" },
      { key: "common.statusClosed", cs: "Uzavřená", en: "Closed" },
      { key: "nav.events", cs: "Akce", en: "Events" },
      { key: "nav.categoryTemplates", cs: "Výchozí kategorie", en: "Default categories" },
      { key: "nav.authors", cs: "Autoři", en: "Authors" },
      { key: "events.title", cs: "Akce", en: "Events" },
      { key: "events.namePlaceholder", cs: "Název akce", en: "Event name" },
      { key: "events.submit", cs: "Vytvořit akci", en: "Create event" },
      { key: "events.errorFillAll", cs: "Vyplňte všechna pole.", en: "Please fill in all fields." },
      { key: "events.errorCreateFailed", cs: "Nepodařilo se vytvořit akci.", en: "Failed to create event." },
      { key: "events.errorDeleteFailed", cs: "Nepodařilo se smazat akci.", en: "Failed to delete event." },
      { key: "events.empty", cs: "Zatím žádné akce.", en: "No events yet." },
      { key: "events.colName", cs: "Název", en: "Name" },
      { key: "events.colFrom", cs: "Od", en: "From" },
      { key: "events.colTo", cs: "Do", en: "To" },
      { key: "events.confirmDelete", cs: "Opravdu smazat akci \"{name}\"?", en: "Really delete event \"{name}\"?" },
      { key: "eventDetail.back", cs: "Zpět na akce", en: "Back to events" },
      { key: "eventDetail.notFound", cs: "Akce nenalezena.", en: "Event not found." },
      { key: "eventDetail.categoriesTitle", cs: "Kategorie a rozpočty", en: "Categories and budgets" },
      { key: "eventDetail.colCategory", cs: "Kategorie", en: "Category" },
      { key: "eventDetail.colBudget", cs: "Rozpočet (Kč)", en: "Budget (CZK)" },
      { key: "eventDetail.total", cs: "Celkem", en: "Total" },
      { key: "eventDetail.newCategoryPlaceholder", cs: "Nová kategorie (jen pro tuto akci)", en: "New category (this event only)" },
      { key: "eventDetail.addCategory", cs: "Přidat kategorii", en: "Add category" },
      { key: "eventDetail.confirmDeleteCategory", cs: "Opravdu smazat tuto kategorii?", en: "Really delete this category?" },
      { key: "eventDetail.errorSaveBudget", cs: "Nepodařilo se uložit rozpočet.", en: "Failed to save budget." },
      { key: "eventDetail.errorAddCategory", cs: "Nepodařilo se přidat kategorii.", en: "Failed to add category." },
      { key: "categoryTemplates.title", cs: "Výchozí kategorie", en: "Default categories" },
      { key: "categoryTemplates.subtitle", cs: "Tento seznam se zkopíruje do každé nově vytvořené akce.", en: "This list is copied into every newly created event." },
      { key: "categoryTemplates.namePlaceholder", cs: "Název kategorie", en: "Category name" },
      { key: "categoryTemplates.empty", cs: "Zatím žádné výchozí kategorie.", en: "No default categories yet." },
      { key: "categoryTemplates.errorAddFailed", cs: "Nepodařilo se přidat kategorii.", en: "Failed to add category." },
      { key: "authors.title", cs: "Autoři", en: "Authors" },
      { key: "authors.namePlaceholder", cs: "Jméno autora", en: "Author name" },
      { key: "authors.bankAccountPlaceholder", cs: "Číslo účtu (volitelné)", en: "Account number (optional)" },
      { key: "authors.bankCodePlaceholder", cs: "Kód banky (volitelné)", en: "Bank code (optional)" },
      { key: "authors.submit", cs: "Přidat autora", en: "Add author" },
      { key: "authors.empty", cs: "Zatím žádní autoři.", en: "No authors yet." },
      { key: "authors.colAccount", cs: "Účet", en: "Account" },
      { key: "authors.statusInactive", cs: "Neaktivní", en: "Inactive" },
      { key: "authors.eventAccessShow", cs: "Přístup k akcím", en: "Event access" },
      { key: "authors.eventAccessHide", cs: "Skrýt akce", en: "Hide events" },
      { key: "authors.eventAccessEmpty", cs: "Zatím žádné akce.", en: "No events yet." },
      { key: "authors.errorAddFailed", cs: "Nepodařilo se přidat autora.", en: "Failed to add author." },
      { key: "authors.errorDeleteFailed", cs: "Nepodařilo se smazat autora.", en: "Failed to delete author." },
      { key: "authors.confirmDelete", cs: "Opravdu smazat autora \"{name}\"?", en: "Really delete author \"{name}\"?" },
      { key: "eventDetail.billsTitle", cs: "Účtenky", en: "Bills" },
      { key: "eventDetail.uploadFiles", cs: "Nahrát soubory", en: "Upload files" },
      { key: "eventDetail.takePhoto", cs: "Vyfotit účtenku", en: "Take photo" },
      { key: "eventDetail.billsEmpty", cs: "Zatím žádné účtenky.", en: "No bills yet." },
      { key: "eventDetail.colFilename", cs: "Soubor", en: "File" },
      { key: "eventDetail.colChannel", cs: "Zdroj", en: "Source" },
      { key: "eventDetail.colCreated", cs: "Nahráno", en: "Uploaded" },
      { key: "eventDetail.channelUpload", cs: "Nahráno ručně", en: "Manual upload" },
      { key: "eventDetail.channelCamera", cs: "Foto", en: "Camera" },
      { key: "eventDetail.channelDrive", cs: "Drive", en: "Drive" },
      { key: "eventDetail.statusNew", cs: "Nové", en: "New" },
      { key: "eventDetail.errorUploadFailed", cs: "Nahrání se nezdařilo.", en: "Upload failed." },
      { key: "eventDetail.uploadResultSummary", cs: "Nahráno: {created}, duplicity: {duplicates}", en: "Uploaded: {created}, duplicates: {duplicates}" },
      { key: "eventDetail.duplicatesTitle", cs: "Duplicity (nebyly nahrány znovu):", en: "Duplicates (not re-uploaded):" },
      { key: "eventDetail.duplicateItem", cs: "{filename} — již nahráno jako \"{existingFilename}\" ({existingDate})", en: "{filename} — already uploaded as \"{existingFilename}\" ({existingDate})" },
      { key: "eventDetail.splitInfoTitle", cs: "Rozdělené PDF soubory:", en: "Split PDF files:" },
      { key: "eventDetail.splitInfoItem", cs: "{filename} rozděleno na {pageCount} stránek", en: "{filename} split into {pageCount} pages" },
      { key: "eventDetail.failuresTitle", cs: "Nepodařilo se zpracovat:", en: "Failed to process:" },
      { key: "eventDetail.failureInvalidPdf", cs: "{filename} — neplatný nebo poškozený PDF soubor", en: "{filename} — invalid or corrupted PDF file" },
      { key: "eventDetail.viewBillsLink", cs: "Zobrazit účtenky ({count})", en: "View bills ({count})" },
      { key: "billsPage.title", cs: "Účtenky", en: "Bills" },
      { key: "billsPage.back", cs: "Zpět na akci", en: "Back to event" },
      { key: "billsPage.filterAll", cs: "Vše", en: "All" },
      { key: "billsPage.statusNew", cs: "Nové", en: "New" },
      { key: "billsPage.statusQueued", cs: "Ve frontě", en: "Queued" },
      { key: "billsPage.statusProcessing", cs: "Zpracovává se", en: "Processing" },
      { key: "billsPage.statusAutoApproved", cs: "Automaticky schváleno", en: "Auto-approved" },
      { key: "billsPage.statusToReview", cs: "Ke kontrole", en: "To review" },
      { key: "billsPage.statusFailed", cs: "Selhalo", en: "Failed" },
      { key: "billsPage.statusApproved", cs: "Schváleno", en: "Approved" },
      { key: "billsPage.colMerchant", cs: "Obchod", en: "Merchant" },
      { key: "billsPage.colAmount", cs: "Částka", en: "Amount" },
      { key: "billsPage.colTotal", cs: "Celkem", en: "Total" },
      { key: "billModal.openFile", cs: "Otevřít soubor v novém okně", en: "Open file in new window" },
      { key: "billModal.merchant", cs: "Obchod / dodavatel", en: "Merchant / supplier" },
      { key: "billModal.date", cs: "Datum", en: "Date" },
      { key: "billModal.amount", cs: "Částka", en: "Amount" },
      { key: "billModal.currency", cs: "Měna", en: "Currency" },
      { key: "billModal.payer", cs: "Zaplatil", en: "Paid by" },
      { key: "billModal.payerEvent", cs: "Akce (bez proplacení)", en: "Event (no reimbursement)" },
      { key: "billModal.notes", cs: "Poznámka", en: "Notes" },
      { key: "billModal.splitTitle", cs: "Rozdělení do kategorií", en: "Category split" },
      { key: "billModal.addSplit", cs: "Přidat kategorii", en: "Add category" },
      { key: "billModal.fillRemainder", cs: "Doplnit zbytek", en: "Fill remainder" },
      { key: "billModal.splitOk", cs: "Součet odpovídá částce.", en: "Split matches the total." },
      { key: "billModal.splitDiff", cs: "Součet: {splitTotal} · zbývá {difference}", en: "Split: {splitTotal} · remaining {difference}" },
      { key: "billModal.approve", cs: "Schválit", en: "Approve" },
      { key: "billModal.reopen", cs: "Znovu otevřít", en: "Reopen" },
      { key: "billModal.saved", cs: "Uloženo.", en: "Saved." },
      { key: "billModal.error.saveFailed", cs: "Uložení se nezdařilo.", en: "Save failed." },
      { key: "billModal.error.approveFailed", cs: "Schválení se nezdařilo.", en: "Approval failed." },
      { key: "billModal.error.reopenFailed", cs: "Znovuotevření se nezdařilo.", en: "Reopen failed." },
      { key: "billModal.error.splitMismatch", cs: "Součet kategorií ({splitTotal}) neodpovídá částce účtenky ({billTotal}).", en: "Category split ({splitTotal}) does not match the bill total ({billTotal})." },
      { key: "billModal.error.missingFields", cs: "Chybí povinné údaje: {fields}", en: "Missing required fields: {fields}" },
      { key: "billModal.error.bill_approved_locked", cs: "Schválenou účtenku nelze upravit — nejdřív ji znovu otevřete.", en: "An approved bill cannot be edited — reopen it first." },
      { key: "billModal.error.event_closed_locked", cs: "Akce je uzavřená, účtenky nelze upravovat.", en: "The event is closed, bills cannot be edited." },
      { key: "billModal.prev", cs: "Předchozí (←)", en: "Previous (←)" },
      { key: "billModal.next", cs: "Další (→)", en: "Next (→)" },
      { key: "billModal.saveAndNext", cs: "Uložit a další", en: "Save and next" },
      { key: "billModal.saveAndStay", cs: "Uložit a zůstat", en: "Save and stay" },
      { key: "billModal.aiReprocess", cs: "Zpracovat AI", en: "Process with AI" },
      { key: "billModal.aiReprocessSoon", cs: "Bude dostupné později", en: "Coming later" },
      { key: "nav.bills", cs: "Účtenky", en: "Bills" },
      { key: "nav.eventSetup", cs: "Nastavení akce", en: "Event setup" },
    ],
    skipDuplicates: true,
  });
}

main().finally(() => prisma.$disconnect());
