import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.user.createMany({
    data: [
      { email: "jana@zare.cz", displayName: "Jana Nováková", role: "admin" },
      { email: "ucetni@zare.cz", displayName: "Účetní", role: "accountant" },
      { email: "1beh@zare.cz", displayName: "1beh", role: "admin" },
    ],
    skipDuplicates: true,
  });

  await prisma.categoryTemplate.createMany({
    data: [
      { name: "potraviny", description: "Necessary food for a multi-day event: ingredients for cooking, bread, groceries, snacks that could reasonably be part of a meal plan. For short events, most food should usually be classified as občerstvení instead, since food is often not necessary." },
      { name: "občerstvení", description: "Extra food or drinks not part of the meal plan: sweets, popcorn, ice cream, food from stalls or restaurants, refreshments. For short events, most food typically belongs here rather than in potraviny." },
      { name: "materiál program", description: "Supplies used for activities, games, crafts, and programme preparation." },
      { name: "materiál provoz LT", description: "Operational camp materials: cleaning supplies, maintenance supplies, equipment needed to run the camp." },
      { name: "doprava účastníků na akci a zpět", description: "Transport of participants to and from the event." },
      { name: "doprava během tábora - výlety", description: "Transport during the camp, including trips and excursions." },
      { name: "vstupné", description: "Tickets, entrance fees, attractions." },
      { name: "odměny", description: "Rewards, prizes, small gifts." },
      { name: "autoprovoz", description: "Car operation costs: fuel, parking, car-related expenses." },
      { name: "stravování", description: "Catering, prepared meals, meal services." },
      { name: "ostatní služby", description: "Other services." },
      { name: "spotřeba EE, plynu a vody ( paušál PS )", description: "Electricity, gas, water — utility lump sum." },
      { name: "jiné výdaje", description: "Use when an expense is valid but does not fit another category, or when no allowed category is suitable." },
      { name: "rezerva", description: "Use only if the receipt clearly relates to a reserve or contingency fund." },
    ],
    skipDuplicates: true,
  });

  await prisma.translation.createMany({
    data: [
      { key: "common.loading", cs: "Načítání...", en: "Loading..." },
      { key: "common.delete", cs: "Smazat", en: "Delete" },
      { key: "common.edit", cs: "Upravit", en: "Edit" },
      { key: "common.save", cs: "Uložit", en: "Save" },
      { key: "common.cancel", cs: "Zrušit", en: "Cancel" },
      { key: "common.add", cs: "Přidat", en: "Add" },
      { key: "common.name", cs: "Jméno", en: "Name" },
      { key: "common.status", cs: "Stav", en: "Status" },
      { key: "common.statusActive", cs: "Aktivní", en: "Active" },
      { key: "common.statusClosed", cs: "Uzavřená", en: "Closed" },
      { key: "nav.events", cs: "Akce", en: "Events" },
      { key: "nav.categoryTemplates", cs: "Výchozí kategorie", en: "Default categories" },
      { key: "nav.authors", cs: "Autoři", en: "Authors" },
      { key: "events.title", cs: "Akce", en: "Events" },
      { key: "events.namePlaceholder", cs: "Název akce", en: "Event name" },
      { key: "events.submit", cs: "Vytvořit akci", en: "Create event" },
      { key: "events.errorFillAll", cs: "Vyplňte všechna pole.", en: "Please fill in all fields." },
      { key: "events.errorCreateFailed", cs: "Nepodařilo se vytvořit akci.", en: "Failed to create event." },
      { key: "events.errorDeleteFailed", cs: "Nepodařilo se smazat akci.", en: "Failed to delete event." },
      { key: "events.empty", cs: "Zatím žádné akce.", en: "No events yet." },
      { key: "events.colName", cs: "Název", en: "Name" },
      { key: "events.colFrom", cs: "Od", en: "From" },
      { key: "events.colTo", cs: "Do", en: "To" },
      { key: "events.confirmDelete", cs: "Opravdu smazat akci \"{name}\"?", en: "Really delete event \"{name}\"?" },
      { key: "eventDetail.back", cs: "Zpět na akce", en: "Back to events" },
      { key: "eventDetail.notFound", cs: "Akce nenalezena.", en: "Event not found." },
      { key: "eventDetail.categoriesTitle", cs: "Kategorie a rozpočty", en: "Categories and budgets" },
      { key: "eventDetail.colCategory", cs: "Kategorie", en: "Category" },
      { key: "eventDetail.colBudget", cs: "Rozpočet (Kč)", en: "Budget (CZK)" },
      { key: "eventDetail.total", cs: "Celkem", en: "Total" },
      { key: "eventDetail.newCategoryPlaceholder", cs: "Nová kategorie (jen pro tuto akci)", en: "New category (this event only)" },
      { key: "eventDetail.addCategory", cs: "Přidat kategorii", en: "Add category" },
      { key: "eventDetail.confirmDeleteCategory", cs: "Opravdu smazat tuto kategorii?", en: "Really delete this category?" },
      { key: "eventDetail.errorSaveBudget", cs: "Nepodařilo se uložit rozpočet.", en: "Failed to save budget." },
      { key: "eventDetail.errorAddCategory", cs: "Nepodařilo se přidat kategorii.", en: "Failed to add category." },
      { key: "categoryTemplates.title", cs: "Výchozí kategorie", en: "Default categories" },
      { key: "categoryTemplates.subtitle", cs: "Tento seznam se zkopíruje do každé nově vytvořené akce.", en: "This list is copied into every newly created event." },
      { key: "categoryTemplates.namePlaceholder", cs: "Název kategorie", en: "Category name" },
      { key: "categoryTemplates.empty", cs: "Zatím žádné výchozí kategorie.", en: "No default categories yet." },
      { key: "categoryTemplates.errorAddFailed", cs: "Nepodařilo se přidat kategorii.", en: "Failed to add category." },
      { key: "authors.title", cs: "Autoři", en: "Authors" },
      { key: "authors.namePlaceholder", cs: "Jméno autora", en: "Author name" },
      { key: "authors.bankAccountPlaceholder", cs: "Číslo účtu (volitelné)", en: "Account number (optional)" },
      { key: "authors.bankCodePlaceholder", cs: "Kód banky (volitelné)", en: "Bank code (optional)" },
      { key: "authors.submit", cs: "Přidat autora", en: "Add author" },
      { key: "authors.empty", cs: "Zatím žádní autoři.", en: "No authors yet." },
      { key: "authors.colAccount", cs: "Účet", en: "Account" },
      { key: "authors.statusInactive", cs: "Neaktivní", en: "Inactive" },
      { key: "authors.eventAccessShow", cs: "Přístup k akcím", en: "Event access" },
      { key: "authors.eventAccessHide", cs: "Skrýt akce", en: "Hide events" },
      { key: "authors.eventAccessEmpty", cs: "Zatím žádné akce.", en: "No events yet." },
      { key: "authors.errorAddFailed", cs: "Nepodařilo se přidat autora.", en: "Failed to add author." },
      { key: "authors.errorDeleteFailed", cs: "Nepodařilo se smazat autora.", en: "Failed to delete author." },
      { key: "authors.confirmDelete", cs: "Opravdu smazat autora \"{name}\"?", en: "Really delete author \"{name}\"?" },
      { key: "eventDetail.billsTitle", cs: "Účtenky", en: "Bills" },
      { key: "eventDetail.uploadFiles", cs: "Nahrát soubory", en: "Upload files" },
      { key: "eventDetail.takePhoto", cs: "Vyfotit účtenku", en: "Take photo" },
      { key: "eventDetail.billsEmpty", cs: "Zatím žádné účtenky.", en: "No bills yet." },
      { key: "eventDetail.colFilename", cs: "Soubor", en: "File" },
      { key: "eventDetail.colChannel", cs: "Zdroj", en: "Source" },
      { key: "eventDetail.colCreated", cs: "Nahráno", en: "Uploaded" },
      { key: "eventDetail.channelUpload", cs: "Nahráno ručně", en: "Manual upload" },
      { key: "eventDetail.channelCamera", cs: "Foto", en: "Camera" },
      { key: "eventDetail.channelDrive", cs: "Drive", en: "Drive" },
      { key: "eventDetail.statusNew", cs: "Nové", en: "New" },
      { key: "eventDetail.errorUploadFailed", cs: "Nahrání se nezdařilo.", en: "Upload failed." },
      { key: "eventDetail.uploadResultSummary", cs: "Nahráno: {created}, duplicity: {duplicates}", en: "Uploaded: {created}, duplicates: {duplicates}" },
      { key: "eventDetail.duplicatesTitle", cs: "Duplicity (nebyly nahrány znovu):", en: "Duplicates (not re-uploaded):" },
      { key: "eventDetail.duplicateItem", cs: "{filename} — již nahráno jako \"{existingFilename}\" ({existingDate})", en: "{filename} — already uploaded as \"{existingFilename}\" ({existingDate})" },
      { key: "eventDetail.splitInfoTitle", cs: "Rozdělené PDF soubory:", en: "Split PDF files:" },
      { key: "eventDetail.splitInfoItem", cs: "{filename} rozděleno na {pageCount} stránek", en: "{filename} split into {pageCount} pages" },
      { key: "eventDetail.failuresTitle", cs: "Nepodařilo se zpracovat:", en: "Failed to process:" },
      { key: "eventDetail.failureInvalidPdf", cs: "{filename} — neplatný nebo poškozený PDF soubor", en: "{filename} — invalid or corrupted PDF file" },
      { key: "eventDetail.viewBillsLink", cs: "Zobrazit účtenky ({count})", en: "View bills ({count})" },
      { key: "billsPage.title", cs: "Účtenky", en: "Bills" },
      { key: "billsPage.back", cs: "Zpět na akci", en: "Back to event" },
      { key: "billsPage.filterAll", cs: "Vše", en: "All" },
      { key: "billsPage.statusNew", cs: "Nové", en: "New" },
      { key: "billsPage.statusQueued", cs: "Ve frontě", en: "Queued" },
      { key: "billsPage.statusProcessing", cs: "Zpracovává se", en: "Processing" },
      { key: "billsPage.statusAutoApproved", cs: "Automaticky schváleno", en: "Auto-approved" },
      { key: "billsPage.statusToReview", cs: "Ke kontrole", en: "To review" },
      { key: "billsPage.statusFailed", cs: "Selhalo", en: "Failed" },
      { key: "billsPage.statusApproved", cs: "Schváleno", en: "Approved" },
      { key: "billsPage.colMerchant", cs: "Obchod", en: "Merchant" },
      { key: "billsPage.colAmount", cs: "Částka", en: "Amount" },
      { key: "billsPage.colTotal", cs: "Celkem", en: "Total" },
      { key: "billModal.openFile", cs: "Otevřít soubor v novém okně", en: "Open file in new window" },
      { key: "billModal.merchant", cs: "Obchod / dodavatel", en: "Merchant / supplier" },
      { key: "billModal.date", cs: "Datum", en: "Date" },
      { key: "billModal.amount", cs: "Částka", en: "Amount" },
      { key: "billModal.currency", cs: "Měna", en: "Currency" },
      { key: "billModal.payer", cs: "Zaplatil", en: "Paid by" },
      { key: "billModal.payerEvent", cs: "Akce (bez proplacení)", en: "Event (no reimbursement)" },
      { key: "billModal.notes", cs: "Poznámka", en: "Notes" },
      { key: "billModal.splitTitle", cs: "Rozdělení do kategorií", en: "Category split" },
      { key: "billModal.addSplit", cs: "Přidat kategorii", en: "Add category" },
      { key: "billModal.fillRemainder", cs: "Doplnit zbytek", en: "Fill remainder" },
      { key: "billModal.splitOk", cs: "Součet odpovídá částce.", en: "Split matches the total." },
      { key: "billModal.splitDiff", cs: "Součet: {splitTotal} · zbývá {difference}", en: "Split: {splitTotal} · remaining {difference}" },
      { key: "billModal.approve", cs: "Schválit", en: "Approve" },
      { key: "billModal.reopen", cs: "Znovu otevřít", en: "Reopen" },
      { key: "billModal.saved", cs: "Uloženo.", en: "Saved." },
      { key: "billModal.error.saveFailed", cs: "Uložení se nezdařilo.", en: "Save failed." },
      { key: "billModal.error.approveFailed", cs: "Schválení se nezdařilo.", en: "Approval failed." },
      { key: "billModal.error.reopenFailed", cs: "Znovuotevření se nezdařilo.", en: "Reopen failed." },
      { key: "billModal.error.splitMismatch", cs: "Součet kategorií ({splitTotal}) neodpovídá částce účtenky ({billTotal}).", en: "Category split ({splitTotal}) does not match the bill total ({billTotal})." },
      { key: "billModal.error.missingFields", cs: "Chybí povinné údaje: {fields}", en: "Missing required fields: {fields}" },
      { key: "billModal.error.bill_approved_locked", cs: "Schválenou účtenku nelze upravit — nejdřív ji znovu otevřete.", en: "An approved bill cannot be edited — reopen it first." },
      { key: "billModal.error.event_closed_locked", cs: "Akce je uzavřená, účtenky nelze upravovat.", en: "The event is closed, bills cannot be edited." },
      { key: "billModal.prev", cs: "Předchozí (←)", en: "Previous (←)" },
      { key: "billModal.next", cs: "Další (→)", en: "Next (→)" },
      { key: "billModal.saveAndNext", cs: "Uložit a další", en: "Save and next" },
      { key: "billModal.saveAndStay", cs: "Uložit a zůstat", en: "Save and stay" },
      { key: "billModal.aiReprocess", cs: "Zpracovat AI", en: "Process with AI" },
      { key: "billModal.aiReprocessSoon", cs: "Bude dostupné později", en: "Coming later" },
      { key: "nav.bills", cs: "Účtenky", en: "Bills" },
      { key: "nav.eventSetup", cs: "Nastavení akce", en: "Event setup" },
      { key: "billsPage.selectedCount", cs: "Vybráno: {count}", en: "Selected: {count}" },
      { key: "billsPage.bulkApprove", cs: "Schválit vybrané", en: "Approve selected" },
      { key: "billsPage.bulkDelete", cs: "Smazat vybrané", en: "Delete selected" },
      { key: "billsPage.clearSelection", cs: "Zrušit výběr", en: "Clear selection" },
      { key: "billsPage.confirmBulkDelete", cs: "Opravdu smazat {count} účtenek? Tuto akci nelze vrátit.", en: "Really delete {count} bills? This cannot be undone." },
      { key: "billsPage.bulkResult", cs: "Hotovo: {succeeded} · nezdařilo se: {failed}", en: "Done: {succeeded} · failed: {failed}" },
      { key: "billsPage.bulkFailed", cs: "Hromadná akce se nezdařila.", en: "Bulk action failed." },
      { key: "billsPage.bulkFailuresTitle", cs: "Nezpracované účtenky:", en: "Bills not processed:" },
      { key: "billsPage.bulkErrMissing", cs: "{filename} — chybí: {fields}", en: "{filename} — missing: {fields}" },
      { key: "billsPage.bulkErrSplit", cs: "{filename} — součet kategorií {splitTotal} ≠ částka {billTotal}", en: "{filename} — split {splitTotal} does not match total {billTotal}" },
      { key: "billsPage.bulkErrApproved", cs: "{filename} — již schváleno", en: "{filename} — already approved" },
      { key: "imageEditor.openButton", cs: "Upravit obrázek", en: "Edit image" },
      { key: "imageEditor.title", cs: "Úprava obrázku", en: "Edit image" },
      { key: "imageEditor.cropHint", cs: "Táhnutím myší vyberte oblast pro oříznutí (volitelné).", en: "Drag to select a crop area (optional)." },
      { key: "imageEditor.blackWhite", cs: "Černobíle", en: "Black and white" },
      { key: "imageEditor.contrast", cs: "Kontrast", en: "Contrast" },
      { key: "imageEditor.brightness", cs: "Jas", en: "Brightness" },
      { key: "imageEditor.apply", cs: "Uložit úpravy", en: "Save changes" },
      { key: "imageEditor.reset", cs: "Zrušit úpravy", en: "Reset" },
      { key: "imageEditor.revert", cs: "Obnovit původní", en: "Restore original" },
      { key: "imageEditor.confirmRevert", cs: "Obnovit původní naskenovaný obrázek a zahodit úpravy?", en: "Restore the original scan and discard edits?" },
      { key: "imageEditor.errorCanvas", cs: "Nepodařilo se připravit obrázek.", en: "Could not prepare the image." },
      { key: "imageEditor.errorExport", cs: "Nepodařilo se vytvořit upravený obrázek.", en: "Could not create the edited image." },
      { key: "imageEditor.errorRevert", cs: "Obnovení se nezdařilo.", en: "Restore failed." },
      { key: "imageEditor.error.duplicate_after_edit", cs: "Upravený obrázek je shodný s jinou účtenkou v této akci.", en: "The edited image matches another bill in this event." },
      { key: "imageEditor.error.pdf_not_editable", cs: "PDF soubory zatím nelze upravovat.", en: "PDF files cannot be edited yet." },
      { key: "imageEditor.error.bill_approved_locked", cs: "Schválenou účtenku nelze upravit.", en: "An approved bill cannot be edited." },
      { key: "imageEditor.error.event_closed_locked", cs: "Akce je uzavřená.", en: "The event is closed." },
      { key: "imageEditor.error.no_original", cs: "Původní obrázek není k dispozici.", en: "No original image available." },
      { key: "imageEditor.cornerHint", cs: "Přetáhněte čtyři rohy na okraje účtenky. Obrázek se narovná do obdélníku.", en: "Drag the four corners onto the edges of the receipt. The image will be straightened into a rectangle." },
      { key: "imageEditor.processing", cs: "Zpracovávám obrázek...", en: "Processing image..." },
      { key: "billsPage.noRate", cs: "kurz není k dispozici", en: "no rate available" },
      { key: "billsPage.totalExcludes", cs: "nezahrnuje {count} účtenek bez kurzu", en: "excludes {count} bills without a rate" },
      { key: "billModal.czkEquivalent", cs: "= {amount} Kč (kurz {rate} ze dne {date})", en: "= {amount} CZK (rate {rate} from {date})" },
      { key: "billModal.czkUnavailable", cs: "Přepočet na Kč není možný — chybí datum účtenky nebo kurz.", en: "CZK conversion unavailable — missing bill date or exchange rate." },
      { key: "billModal.error.missingFields.amountCzk", cs: "přepočet na Kč", en: "CZK amount" },
      { key: "nav.exchangeRates", cs: "Kurzy", en: "Exchange rates" },
      { key: "rates.title", cs: "Kurzy ČNB", en: "CNB exchange rates" },
      { key: "rates.subtitle", cs: "Denní kurzy devizového trhu. Aktualizují se automaticky v pracovní dny odpoledne.", en: "Daily central bank fixing rates. Updated automatically on weekday afternoons." },
      { key: "rates.fetchToday", cs: "Načíst dnešní kurz", en: "Fetch today rate" },
      { key: "rates.fetchTodayHint", cs: "ČNB vyhlašuje kurzy v pracovní dny kolem 14:30.", en: "CNB publishes rates on business days around 14:30." },
      { key: "rates.fetchDate", cs: "Načíst pro datum", en: "Fetch for date" },
      { key: "rates.backfill", cs: "Doplnit historii", en: "Backfill history" },
      { key: "rates.backfillHint", cs: "Počet dní zpět (max 60).", en: "Days back (max 60)." },
      { key: "rates.syncDone", cs: "Kurzy načteny pro {date}.", en: "Rates loaded for {date}." },
      { key: "rates.backfillDone", cs: "Doplněno {count} obchodních dní.", en: "Backfilled {count} business days." },
      { key: "rates.syncFailed", cs: "Načtení kurzů selhalo: {error}", en: "Loading rates failed: {error}" },
      { key: "rates.recalcTitle", cs: "Dopočet účtenek", en: "Recalculate bills" },
      { key: "rates.recalcPending", cs: "{count} účtenek čeká na přepočet do Kč.", en: "{count} bills are waiting for CZK conversion." },
      { key: "rates.recalcNone", cs: "Všechny účtenky mají přepočet do Kč.", en: "All bills have a CZK amount." },
      { key: "rates.recalcButton", cs: "Přepočítat účtenky", en: "Recalculate bills" },
      { key: "rates.recalcNote", cs: "Schválené účtenky se nikdy nepřepočítávají — jejich kurz zůstává zachován.", en: "Approved bills are never recalculated — their stored rate is preserved." },
      { key: "rates.recalcDone", cs: "Přepočítáno: {converted}, stále bez kurzu: {stillMissing}", en: "Converted: {converted}, still without a rate: {stillMissing}" },
      { key: "rates.recalcFailed", cs: "Přepočet selhal.", en: "Recalculation failed." },
      { key: "rates.tableTitle", cs: "Uložené kurzy", en: "Stored rates" },
      { key: "rates.colDate", cs: "Datum", en: "Date" },
      { key: "rates.empty", cs: "Zatím žádné kurzy.", en: "No rates yet." },
      { key: "driveSettings.title", cs: "Napojení na Google Drive", en: "Google Drive integration" },
      { key: "driveSettings.serviceAccountLabel", cs: "Servisní účet", en: "Service account" },
      { key: "driveSettings.instructionsIntro", cs: "Aby aplikace mohla číst a zapisovat soubory, nasdílejte příslušné složky na Google Drive s tímto servisním účtem:", en: "For the app to read and write files, share the relevant Drive folders with this service account:" },
      { key: "driveSettings.instructionsSteps", cs: "1. Otevřete složku na Google Drive.\n2. Klikněte pravým tlačítkem na složku a vyberte Sdílet.\n3. Vložte e-mail servisního účtu výše a nastavte roli Editor.", en: "1. Open the folder in Google Drive.\n2. Right-click the folder and choose Share.\n3. Paste the service account email above and set the role to Editor." },
      { key: "driveSettings.ingestFolderLabel", cs: "ID složky pro import účtenek", en: "Bill ingest folder ID" },
      { key: "driveSettings.exportFolderLabel", cs: "ID složky pro export", en: "Export folder ID" },
      { key: "driveSettings.folderIdHint", cs: "ID najdete v adrese složky na Google Drive, za /folders/.", en: "Find it in the folder's Drive URL, after /folders/." },
      { key: "driveSettings.saveFolders", cs: "Uložit složky", en: "Save folders" },
      { key: "driveSettings.errorSaveFailed", cs: "Nepodařilo se uložit nastavení Drive.", en: "Failed to save Drive settings." },
      { key: "driveSettings.testConnection", cs: "Otestovat připojení", en: "Test connection" },
      { key: "driveSettings.testing", cs: "Testuji...", en: "Testing..." },
      { key: "driveSettings.testResultAccessible", cs: "Přístup funguje ({name})", en: "Access works ({name})" },
      { key: "driveSettings.testResultIngestLabel", cs: "Import:", en: "Ingest:" },
      { key: "driveSettings.testResultExportLabel", cs: "Export:", en: "Export:" },
      { key: "driveSettings.noFoldersSet", cs: "Nejdřív vyplňte a uložte alespoň jedno ID složky.", en: "Fill in and save at least one folder ID first." },
      { key: "driveSettings.error.wrong_type", cs: "ID nepatří složce (jiný typ souboru).", en: "ID does not point to a folder (different file type)." },
      { key: "driveSettings.error.not_found", cs: "Složka nenalezena — zkontrolujte ID.", en: "Folder not found — check the ID." },
      { key: "driveSettings.error.access_denied", cs: "Přístup odepřen — složka není nasdílená se servisním účtem.", en: "Access denied — the folder is not shared with the service account." },
      { key: "driveSettings.error.unknown", cs: "Neznámá chyba při ověřování přístupu.", en: "Unknown error while checking access." },
      { key: "driveSettings.importButton", cs: "Importovat nyní", en: "Import now" },
      { key: "driveSettings.importing", cs: "Importuji...", en: "Importing..." },
      { key: "driveSettings.importNoFolderSet", cs: "Nejdřív nastavte a uložte složku pro import.", en: "Set and save the ingest folder first." },
      { key: "driveSettings.importResultSummary", cs: "Vytvořeno: {created}, duplicity: {duplicates}", en: "Created: {created}, duplicates: {duplicates}" },
      { key: "driveSettings.importAuthorsSummary", cs: "Autoři: {matched} spárováno, {created} nově vytvořeno", en: "Authors: {matched} matched, {created} newly created" },
      { key: "driveSettings.importSkippedAlready", cs: "Přeskočeno (již dříve importováno): {count}", en: "Skipped (already imported before): {count}" },
      { key: "driveSettings.importSkippedNativeTitle", cs: "Přeskočené soubory Google (nelze importovat jako účtenku):", en: "Skipped Google files (cannot be imported as a bill):" },
      { key: "driveSettings.importSkippedNativeItem", cs: "{filename} (složka {subfolderName})", en: "{filename} (folder {subfolderName})" },
      { key: "driveSettings.error.event_closed_locked", cs: "Akce je uzavřená, import není možný.", en: "The event is closed, import is not possible." },
      { key: "driveSettings.error.no_ingest_folder", cs: "Nejdřív nastavte a uložte složku pro import.", en: "Set and save the ingest folder first." },
      { key: "driveSettings.error.event_not_found", cs: "Akce nenalezena.", en: "Event not found." },
      { key: "driveSettings.error.generic", cs: "Import se nezdařil.", en: "Import failed." },
    ],
    skipDuplicates: true,
  });
}

main().finally(() => prisma.$disconnect());
