import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.user.createMany({
    data: [
      { email: "jana@zare.cz", displayName: "Jana Nováková", role: "admin" },
      { email: "ucetni@zare.cz", displayName: "Účetní", role: "accountant" },
      { email: "1beh@zare.cz", displayName: "1beh", role: "admin" },
    ],
    skipDuplicates: true,
  });

  await prisma.categoryTemplate.createMany({
    data: [
      { name: "potraviny", description: "Necessary food for a multi-day event: ingredients for cooking, bread, groceries, snacks that could reasonably be part of a meal plan. For short events, most food should usually be classified as občerstvení instead, since food is often not necessary." },
      { name: "občerstvení", description: "Extra food or drinks not part of the meal plan: sweets, popcorn, ice cream, food from stalls or restaurants, refreshments. For short events, most food typically belongs here rather than in potraviny." },
      { name: "materiál program", description: "Supplies used for activities, games, crafts, and programme preparation." },
      { name: "materiál provoz LT", description: "Operational camp materials: cleaning supplies, maintenance supplies, equipment needed to run the camp." },
      { name: "doprava účastníků na akci a zpět", description: "Transport of participants to and from the event." },
      { name: "doprava během tábora - výlety", description: "Transport during the camp, including trips and excursions." },
      { name: "vstupné", description: "Tickets, entrance fees, attractions." },
      { name: "odměny", description: "Rewards, prizes, small gifts." },
      { name: "autoprovoz", description: "Car operation costs: fuel, parking, car-related expenses." },
      { name: "stravování", description: "Catering, prepared meals, meal services." },
      { name: "ostatní služby", description: "Other services." },
      { name: "spotřeba EE, plynu a vody ( paušál PS )", description: "Electricity, gas, water — utility lump sum." },
      { name: "jiné výdaje", description: "Use when an expense is valid but does not fit another category, or when no allowed category is suitable." },
      { name: "rezerva", description: "Use only if the receipt clearly relates to a reserve or contingency fund." },
    ],
    skipDuplicates: true,
  });

  await prisma.translation.createMany({
    data: [
      { key: "common.loading", cs: "Načítání...", en: "Loading..." },
      { key: "common.delete", cs: "Smazat", en: "Delete" },
      { key: "common.edit", cs: "Upravit", en: "Edit" },
      { key: "common.save", cs: "Uložit", en: "Save" },
      { key: "common.cancel", cs: "Zrušit", en: "Cancel" },
      { key: "common.add", cs: "Přidat", en: "Add" },
      { key: "common.name", cs: "Jméno", en: "Name" },
      { key: "common.status", cs: "Stav", en: "Status" },
      { key: "common.statusActive", cs: "Aktivní", en: "Active" },
      { key: "common.statusClosed", cs: "Uzavřená", en: "Closed" },
      { key: "nav.events", cs: "Akce", en: "Events" },
      { key: "nav.categoryTemplates", cs: "Výchozí kategorie", en: "Default categories" },
      { key: "nav.authors", cs: "Autoři", en: "Authors" },
      { key: "events.title", cs: "Akce", en: "Events" },
      { key: "events.namePlaceholder", cs: "Název akce", en: "Event name" },
      { key: "events.submit", cs: "Vytvořit akci", en: "Create event" },
      { key: "events.errorFillAll", cs: "Vyplňte všechna pole.", en: "Please fill in all fields." },
      { key: "events.errorCreateFailed", cs: "Nepodařilo se vytvořit akci.", en: "Failed to create event." },
      { key: "events.errorDeleteFailed", cs: "Nepodařilo se smazat akci.", en: "Failed to delete event." },
      { key: "events.empty", cs: "Zatím žádné akce.", en: "No events yet." },
      { key: "events.colName", cs: "Název", en: "Name" },
      { key: "events.colFrom", cs: "Od", en: "From" },
      { key: "events.colTo", cs: "Do", en: "To" },
      { key: "events.confirmDelete", cs: "Opravdu smazat akci \"{name}\"?", en: "Really delete event \"{name}\"?" },
      { key: "eventDetail.back", cs: "Zpět na akce", en: "Back to events" },
      { key: "eventDetail.notFound", cs: "Akce nenalezena.", en: "Event not found." },
      { key: "eventDetail.categoriesTitle", cs: "Kategorie a rozpočty", en: "Categories and budgets" },
      { key: "eventDetail.colCategory", cs: "Kategorie", en: "Category" },
      { key: "eventDetail.colBudget", cs: "Rozpočet (Kč)", en: "Budget (CZK)" },
      { key: "eventDetail.total", cs: "Celkem", en: "Total" },
      { key: "eventDetail.newCategoryPlaceholder", cs: "Nová kategorie (jen pro tuto akci)", en: "New category (this event only)" },
      { key: "eventDetail.addCategory", cs: "Přidat kategorii", en: "Add category" },
      { key: "eventDetail.confirmDeleteCategory", cs: "Opravdu smazat tuto kategorii?", en: "Really delete this category?" },
      { key: "eventDetail.errorSaveBudget", cs: "Nepodařilo se uložit rozpočet.", en: "Failed to save budget." },
      { key: "eventDetail.errorAddCategory", cs: "Nepodařilo se přidat kategorii.", en: "Failed to add category." },
      { key: "categoryTemplates.title", cs: "Výchozí kategorie", en: "Default categories" },
      { key: "categoryTemplates.subtitle", cs: "Tento seznam se zkopíruje do každé nově vytvořené akce.", en: "This list is copied into every newly created event." },
      { key: "categoryTemplates.namePlaceholder", cs: "Název kategorie", en: "Category name" },
      { key: "categoryTemplates.empty", cs: "Zatím žádné výchozí kategorie.", en: "No default categories yet." },
      { key: "categoryTemplates.errorAddFailed", cs: "Nepodařilo se přidat kategorii.", en: "Failed to add category." },
      { key: "categoryTemplates.errorEditFailed", cs: "Nepodařilo se upravit kategorii.", en: "Failed to update category." },
      { key: "categoryTemplates.descriptionPlaceholder", cs: "Popis (nepovinné)", en: "Description (optional)" },
      { key: "authors.title", cs: "Autoři", en: "Authors" },
      { key: "authors.namePlaceholder", cs: "Jméno autora", en: "Author name" },
      { key: "authors.bankAccountPlaceholder", cs: "Číslo účtu (volitelné)", en: "Account number (optional)" },
      { key: "authors.bankCodePlaceholder", cs: "Kód banky (volitelné)", en: "Bank code (optional)" },
      { key: "authors.submit", cs: "Přidat autora", en: "Add author" },
      { key: "authors.empty", cs: "Zatím žádní autoři.", en: "No authors yet." },
      { key: "authors.colAccount", cs: "Účet", en: "Account" },
      { key: "authors.statusInactive", cs: "Neaktivní", en: "Inactive" },
      { key: "authors.eventAccessShow", cs: "Přístup k akcím", en: "Event access" },
      { key: "authors.eventAccessHide", cs: "Skrýt akce", en: "Hide events" },
      { key: "authors.eventAccessEmpty", cs: "Zatím žádné akce.", en: "No events yet." },
      { key: "authors.errorAddFailed", cs: "Nepodařilo se přidat autora.", en: "Failed to add author." },
      { key: "authors.errorDeleteFailed", cs: "Nepodařilo se smazat autora.", en: "Failed to delete author." },
      { key: "authors.errorEditFailed", cs: "Nepodařilo se uložit změny.", en: "Failed to save changes." },
      { key: "authors.mergeButton", cs: "Sloučit", en: "Merge" },
      { key: "authors.mergeTargetPlaceholder", cs: "Vyberte cílového autora", en: "Select target author" },
      { key: "authors.mergeConfirmButton", cs: "Potvrdit sloučení", en: "Confirm merge" },
      { key: "authors.mergeConfirmDialog", cs: "Opravdu sloučit \"{source}\" do \"{target}\"? Účtenky a přístup k akcím se přesunou, autor \"{source}\" bude archivován.", en: "Really merge \"{source}\" into \"{target}\"? Bills and event access will move over, and \"{source}\" will be archived." },
      { key: "authors.mergedBadge", cs: "Sloučeno do: {name}", en: "Merged into: {name}" },
      { key: "authors.errorMergeFailed", cs: "Sloučení se nezdařilo.", en: "Merge failed." },
      { key: "authors.error.cannot_merge_self", cs: "Nelze sloučit autora sám se sebou.", en: "Cannot merge an author into itself." },
      { key: "authors.error.already_merged", cs: "Tento autor je již sloučen.", en: "This author has already been merged." },
      { key: "authors.error.target_inactive", cs: "Cílový autor není aktivní.", en: "Target author is not active." },
      { key: "authors.error.source_not_found", cs: "Zdrojový autor nenalezen.", en: "Source author not found." },
      { key: "authors.error.target_not_found", cs: "Cílový autor nenalezen.", en: "Target author not found." },
      { key: "nav.users", cs: "Uživatelé", en: "Users" },
      { key: "nav.budget", cs: "Čerpání rozpočtu", en: "Budget Spending" },
      { key: "nav.payments", cs: "Platby", en: "Payments" },
      { key: "nav.currentEvent", cs: "Aktuální akce", en: "Current event" },
      { key: "nav.organization", cs: "Organizace", en: "Organization" },
      { key: "nav.sectionBills", cs: "Modul Účtenky", en: "Bills module" },
      { key: "nav.sectionHealth", cs: "Modul Zdraví", en: "Health module" },
      { key: "nav.toggleTheme", cs: "Přepnout motiv", en: "Toggle theme" },
      { key: "nav.openMenu", cs: "Otevřít menu", en: "Open menu" },
      { key: "usersPage.title", cs: "Uživatelé", en: "Users" },
      { key: "usersPage.emailPlaceholder", cs: "E-mail", en: "Email" },
      { key: "usersPage.namePlaceholder", cs: "Jméno", en: "Name" },
      { key: "usersPage.roleAdmin", cs: "Administrátor", en: "Admin" },
      { key: "usersPage.roleAccountant", cs: "Účetní", en: "Accountant" },
      { key: "usersPage.roleUser", cs: "Uživatel", en: "User" },
      { key: "usersPage.submit", cs: "Přidat uživatele", en: "Add user" },
      { key: "usersPage.colEmail", cs: "E-mail", en: "Email" },
      { key: "usersPage.colRole", cs: "Role", en: "Role" },
      { key: "usersPage.empty", cs: "Zatím žádní uživatelé.", en: "No users yet." },
      { key: "usersPage.errorAddFailed", cs: "Nepodařilo se přidat uživatele.", en: "Failed to add user." },
      { key: "usersPage.errorEditFailed", cs: "Nepodařilo se uložit změny.", en: "Failed to save changes." },
      { key: "usersPage.error.forbidden", cs: "Tuto stránku může použít pouze administrátor.", en: "Only an admin can use this page." },
      { key: "usersPage.error.duplicate_email", cs: "Tento e-mail je již zaregistrován.", en: "This email is already registered." },
      { key: "usersPage.error.cannot_deactivate_self", cs: "Nemůžete deaktivovat sám sebe.", en: "You cannot deactivate yourself." },
      { key: "usersPage.error.cannot_demote_self", cs: "Nemůžete si sami odebrat roli administrátora.", en: "You cannot remove your own admin role." },
      { key: "authors.confirmDelete", cs: "Opravdu smazat autora \"{name}\"?", en: "Really delete author \"{name}\"?" },
      { key: "eventDetail.billsTitle", cs: "Účtenky", en: "Bills" },
      { key: "eventDetail.uploadFiles", cs: "Nahrát soubory", en: "Upload files" },
      { key: "eventDetail.takePhoto", cs: "Vyfotit účtenku", en: "Take photo" },
      { key: "eventDetail.billsEmpty", cs: "Zatím žádné účtenky.", en: "No bills yet." },
      { key: "eventDetail.colFilename", cs: "Soubor", en: "File" },
      { key: "eventDetail.colChannel", cs: "Zdroj", en: "Source" },
      { key: "eventDetail.colCreated", cs: "Nahráno", en: "Uploaded" },
      { key: "eventDetail.channelUpload", cs: "Nahráno ručně", en: "Manual upload" },
      { key: "eventDetail.channelCamera", cs: "Foto", en: "Camera" },
      { key: "eventDetail.channelDrive", cs: "Drive", en: "Drive" },
      { key: "eventDetail.statusNew", cs: "Nové", en: "New" },
      { key: "eventDetail.errorUploadFailed", cs: "Nahrání se nezdařilo.", en: "Upload failed." },
      { key: "eventDetail.uploadResultSummary", cs: "Nahráno: {created}, duplicity: {duplicates}", en: "Uploaded: {created}, duplicates: {duplicates}" },
      { key: "eventDetail.duplicatesTitle", cs: "Duplicity (nebyly nahrány znovu):", en: "Duplicates (not re-uploaded):" },
      { key: "eventDetail.duplicateItem", cs: "{filename} — již nahráno jako \"{existingFilename}\" ({existingDate})", en: "{filename} — already uploaded as \"{existingFilename}\" ({existingDate})" },
      { key: "eventDetail.splitInfoTitle", cs: "Rozdělené PDF soubory:", en: "Split PDF files:" },
      { key: "eventDetail.splitInfoItem", cs: "{filename} rozděleno na {pageCount} stránek", en: "{filename} split into {pageCount} pages" },
      { key: "eventDetail.failuresTitle", cs: "Nepodařilo se zpracovat:", en: "Failed to process:" },
      { key: "eventDetail.failureInvalidPdf", cs: "{filename} — neplatný nebo poškozený PDF soubor", en: "{filename} — invalid or corrupted PDF file" },
      { key: "eventDetail.viewBillsLink", cs: "Zobrazit účtenky ({count})", en: "View bills ({count})" },
      { key: "eventDetail.syncFromTemplates", cs: "Synchronizovat se šablonami", en: "Sync from templates" },
      { key: "eventDetail.errorSyncFailed", cs: "Synchronizace se nezdařila.", en: "Sync failed." },
      { key: "eventDetail.closeButton", cs: "Uzavřít akci", en: "Close event" },
      { key: "eventDetail.reopenButton", cs: "Znovu otevřít akci", en: "Reopen event" },
      { key: "eventDetail.confirmClose", cs: "Opravdu uzavřít akci? Účtenky budou needatelné pro úpravy, dokud akci znovu neotevřete.", en: "Really close the event? Bills will be locked for editing until you reopen it." },
      { key: "eventDetail.confirmReopen", cs: "Opravdu znovu otevřít akci?", en: "Really reopen the event?" },
      { key: "eventDetail.closedAtLabel", cs: "Uzavřeno: {date}", en: "Closed: {date}" },
      { key: "eventDetail.error.event_already_closed", cs: "Akce je již uzavřená.", en: "The event is already closed." },
      { key: "eventDetail.error.event_already_active", cs: "Akce je již aktivní.", en: "The event is already active." },
      { key: "eventDetail.error.admin_only", cs: "Tuto akci může provést pouze administrátor.", en: "Only an admin can perform this action." },
      { key: "eventDetail.error.lifecycleGeneric", cs: "Akci se nepodařilo změnit.", en: "Failed to change the event's status." },
      { key: "billsPage.title", cs: "Účtenky", en: "Bills" },
      { key: "billsPage.back", cs: "Zpět na akci", en: "Back to event" },
      { key: "billsPage.filterAll", cs: "Vše", en: "All" },
      { key: "billsPage.statusNew", cs: "Nové", en: "New" },
      { key: "billsPage.statusQueued", cs: "Ve frontě", en: "Queued" },
      { key: "billsPage.statusProcessing", cs: "Zpracovává se", en: "Processing" },
      { key: "billsPage.statusAutoApproved", cs: "Automaticky schváleno", en: "Auto-approved" },
      { key: "billsPage.statusToReview", cs: "Ke kontrole", en: "To review" },
      { key: "billsPage.statusFailed", cs: "Selhalo", en: "Failed" },
      { key: "billsPage.statusApproved", cs: "Schváleno", en: "Approved" },
      { key: "billsPage.colMerchant", cs: "Obchod", en: "Merchant" },
      { key: "billsPage.colAmount", cs: "Částka", en: "Amount" },
      { key: "billsPage.colTotal", cs: "Celkem", en: "Total" },
      { key: "billModal.openFile", cs: "Otevřít soubor v novém okně", en: "Open file in new window" },
      { key: "billModal.merchant", cs: "Obchod / dodavatel", en: "Merchant / supplier" },
      { key: "billModal.date", cs: "Datum", en: "Date" },
      { key: "billModal.amount", cs: "Částka", en: "Amount" },
      { key: "billModal.currency", cs: "Měna", en: "Currency" },
      { key: "billModal.payer", cs: "Zaplatil", en: "Paid by" },
      { key: "billModal.payerEvent", cs: "Akce (bez proplacení)", en: "Event (no reimbursement)" },
      { key: "billModal.notes", cs: "Poznámka", en: "Notes" },
      { key: "billModal.splitTitle", cs: "Rozdělení do kategorií", en: "Category split" },
      { key: "billModal.addSplit", cs: "Přidat kategorii", en: "Add category" },
      { key: "billModal.fillRemainder", cs: "Doplnit zbytek", en: "Fill remainder" },
      { key: "billModal.splitOk", cs: "Součet odpovídá částce.", en: "Split matches the total." },
      { key: "billModal.splitDiff", cs: "Součet: {splitTotal} · zbývá {difference}", en: "Split: {splitTotal} · remaining {difference}" },
      { key: "billModal.approve", cs: "Schválit", en: "Approve" },
      { key: "billModal.reopen", cs: "Znovu otevřít", en: "Reopen" },
      { key: "billModal.saved", cs: "Uloženo.", en: "Saved." },
      { key: "billModal.error.saveFailed", cs: "Uložení se nezdařilo.", en: "Save failed." },
      { key: "billModal.error.approveFailed", cs: "Schválení se nezdařilo.", en: "Approval failed." },
      { key: "billModal.error.reopenFailed", cs: "Znovuotevření se nezdařilo.", en: "Reopen failed." },
      { key: "billModal.error.splitMismatch", cs: "Součet kategorií ({splitTotal}) neodpovídá částce účtenky ({billTotal}).", en: "Category split ({splitTotal}) does not match the bill total ({billTotal})." },
      { key: "billModal.error.missingFields", cs: "Chybí povinné údaje: {fields}", en: "Missing required fields: {fields}" },
      { key: "billModal.error.bill_approved_locked", cs: "Schválenou účtenku nelze upravit — nejdřív ji znovu otevřete.", en: "An approved bill cannot be edited — reopen it first." },
      { key: "billModal.error.event_closed_locked", cs: "Akce je uzavřená, účtenky nelze upravovat.", en: "The event is closed, bills cannot be edited." },
      { key: "billModal.prev", cs: "Předchozí (←)", en: "Previous (←)" },
      { key: "billModal.backToBills", cs: "Zpět na doklady", en: "Back to bills" },
      { key: "billModal.aiProcessing", cs: "Zpracovávám...", en: "Processing..." },
      { key: "billModal.aiProcessDone", cs: "Zpracováno AI.", en: "Processed by AI." },
      { key: "billModal.aiProcessFailed", cs: "Zpracování AI selhalo.", en: "AI processing failed." },
      { key: "billModal.error.no_categories", cs: "Akce nemá žádné kategorie.", en: "Event has no categories." },
      { key: "billModal.error.ai_call_failed", cs: "Volání AI služby selhalo.", en: "AI service call failed." },
      { key: "billsPage.confirmBulkAi", cs: "Opravdu spustit AI zpracování pro {count} účtenek? Zůstaňte na této stránce, dokud zpracování neskončí.", en: "Really run AI processing for {count} bills? Stay on this page until it finishes." },
      { key: "billsPage.bulkAiTooMany", cs: "Najednou lze zpracovat maximálně {max} účtenek. Vyberte prosím méně.", en: "You can process at most {max} bills at once. Please select fewer." },
      { key: "billsPage.bulkAiFailed", cs: "Hromadné zpracování AI se nezdařilo.", en: "Bulk AI processing failed." },
      { key: "billModal.aiFailureReason", cs: "Důvod selhání AI: {reason}", en: "AI failure reason: {reason}" },
      { key: "events.error.event_has_bills", cs: "Tuto akci nelze smazat, protože obsahuje {count} dokladů. Nejprve doklady přesuňte nebo smažte.", en: "This event cannot be deleted because it contains {count} bills. Move or delete the bills first." },
      { key: "events.error.event_has_dependencies", cs: "Tuto akci nelze smazat kvůli existujícím závislostem (kategorie nebo přístupy).", en: "This event cannot be deleted due to existing dependencies (categories or access grants)." },
      { key: "paymentsPage.paidSectionTitle", cs: "Již vyplaceno", en: "Already paid" },
      { key: "paymentsPage.unmarkPaidButton", cs: "Zrušit vyplacení", en: "Unmark as paid" },
      { key: "paymentsPage.unmarkPaidConfirm", cs: "Opravdu zrušit vyplacení {count} dokladů pro {name}?", en: "Really unmark {count} bills as paid for {name}?" },
      { key: "paymentsPage.unmarkPaidFailed", cs: "Zrušení vyplacení se nezdařilo.", en: "Unmarking as paid failed." },
      { key: "billsPage.bulkMarkPaid", cs: "Označit jako vyplaceno", en: "Mark as paid" },
      { key: "billsPage.bulkMarkUnpaid", cs: "Zrušit vyplacení", en: "Mark as unpaid" },
      { key: "billsPage.bulkErrNoPayer", cs: "{filename}: nemá přiřazeného plátce, přeskočeno.", en: "{filename}: has no payer assigned, skipped." },
      { key: "billModal.paidStatus", cs: "Stav platby", en: "Payment status" },
      { key: "billModal.paidChangeFailed", cs: "Změna stavu platby se nezdařila.", en: "Changing payment status failed." },
      { key: "paymentsPage.scopeApproved", cs: "Pouze schválené", en: "Approved only" },
      { key: "paymentsPage.scopeAll", cs: "Všechny", en: "All" },
      { key: "billsPage.bulkAiActive", cs: "{count} účtenek se právě zpracovává AI.", en: "{count} bills are currently being processed by AI." },
      { key: "billModal.error.bill_processing_locked", cs: "Účtenka se právě zpracovává AI, počkejte prosím.", en: "This bill is currently being processed by AI, please wait." },
      { key: "billModal.moveToEvent", cs: "Přesunout do jiné akce...", en: "Move to another event..." },
      { key: "billModal.moveConfirm", cs: "Opravdu přesunout tuto účtenku do akce \u201e{name}\u201c? Kategorie budou přemapovány podle názvu, nespárované budou vymazány.", en: "Really move this bill to \u201c{name}\u201d? Categories will be remapped by name; unmatched ones will be cleared." },
      { key: "billModal.moveFailed", cs: "Přesun se nezdařil.", en: "Move failed." },
      { key: "billModal.moveDone", cs: "Přesunuto. Spárováno kategorií: {matched}, vymazáno: {dropped}.", en: "Moved. Categories matched: {matched}, cleared: {dropped}." },
      { key: "billModal.error.target_event_not_found", cs: "Cílová akce nebyla nalezena.", en: "Target event not found." },
      { key: "billModal.error.already_in_event", cs: "Účtenka už je v této akci.", en: "Bill is already in this event." },
      { key: "imageEditor.loadingPdf", cs: "Načítám PDF...", en: "Loading PDF..." },
      { key: "imageEditor.errorPdfRender", cs: "Nepodařilo se načíst PDF pro úpravu.", en: "Failed to load the PDF for editing." },
      { key: "billsPage.bulkMoveButton", cs: "Přesunout do...", en: "Move to..." },
      { key: "billsPage.bulkMoveConfirm", cs: "Opravdu přesunout {count} účtenek do akce \u201e{name}\u201c?", en: "Really move {count} bills to \u201c{name}\u201d?" },
      { key: "billsPage.bulkMoveSelectPlaceholder", cs: "Vyberte cílovou akci", en: "Select target event" },
      { key: "billsPage.bulkMoveConfirmButton", cs: "Potvrdit přesun", en: "Confirm move" },
      { key: "billsPage.bulkErrApprovedLocked", cs: "{filename}: je schválena, nejprve ji otevřete.", en: "{filename}: is approved, reopen it first." },
      { key: "billsPage.bulkErrEventClosed", cs: "{filename}: akce je uzavřena.", en: "{filename}: event is closed." },
      { key: "importPage.navLink", cs: "Import s náhledem", en: "Import with review" },
      { key: "importPage.title", cs: "Import účtenek", en: "Import bills" },
      { key: "importPage.dropzoneHint", cs: "Přetáhněte soubory sem, nebo použijte tlačítka níže", en: "Drag files here, or use the buttons below" },
      { key: "importPage.ingestSummary", cs: "Duplicity: {duplicates} \u00b7 rozdělené PDF: {splits} \u00b7 chyby: {failures}", en: "Duplicates: {duplicates} \u00b7 split PDFs: {splits} \u00b7 failures: {failures}" },
      { key: "importPage.colFile", cs: "Soubor", en: "File" },
      { key: "importPage.colMerchant", cs: "Obchod", en: "Merchant" },
      { key: "importPage.colAuthor", cs: "Plátce", en: "Payer" },
      { key: "importPage.colDate", cs: "Datum", en: "Date" },
      { key: "importPage.colPaid", cs: "Vyplaceno", en: "Paid" },
      { key: "importPage.merchantPlaceholder", cs: "Obchod (nepovinné)", en: "Merchant (optional)" },
      { key: "importPage.paidLabel", cs: "Již vyplaceno", en: "Already paid" },
      { key: "importPage.unlockRow", cs: "Upravit zvlášť", en: "Edit separately" },
      { key: "importPage.lockRow", cs: "Zpět na hromadné", en: "Back to bulk" },
      { key: "importPage.reprocessAiLabel", cs: "Ihned zpracovat pomocí AI", en: "Process with AI immediately" },
      { key: "importPage.confirmButton", cs: "Potvrdit a dokončit", en: "Confirm and finish" },
      { key: "importPage.doneMessage", cs: "Hotovo — {count} účtenek importováno.", en: "Done — {count} bills imported." },
      { key: "importPage.goToBills", cs: "Přejít na seznam účtenek", en: "Go to bills list" },
      { key: "importPage.confirmPartialFailure", cs: "{count} účtenek se nepodařilo nastavit \u2014 zkontrolujte je prosím v seznamu.", en: "{count} bills could not be updated \u2014 please check them in the list." },
      { key: "importPage.aiTriggerFailed", cs: "Spuštění AI zpracování selhalo \u2014 můžete ho spustit ručně ze seznamu účtenek.", en: "Starting AI processing failed \u2014 you can trigger it manually from the bills list." },
      { key: "importPage.colCategory", cs: "Kategorie", en: "Category" },
      { key: "importPage.noCategoryOption", cs: "\u2014 bez kategorie \u2014", en: "\u2014 no category \u2014" },
      { key: "importPage.driveImportButton", cs: "Import z Google Drive", en: "Import from Google Drive" },
      { key: "importPage.driveImportFailed", cs: "Import z Drive selhal.", en: "Import from Drive failed." },
      { key: "importPage.error.no_ingest_folder", cs: "Tato akce nemá nastavenou složku pro import.", en: "This event has no import folder configured." },
      { key: "importPage.error.event_not_found", cs: "Akce nebyla nalezena.", en: "Event not found." },
      { key: "nav.import", cs: "Import", en: "Import" },
      { key: "billModal.aiLockedNotice", cs: "AI právě zpracovává tuto účtenku. Jakmile skončí, stránka se aktualizuje automaticky.", en: "AI is currently processing this bill. This page will update automatically once it is done." },
      { key: "billModal.next", cs: "Další (→)", en: "Next (→)" },
      { key: "billModal.saveAndNext", cs: "Uložit a další", en: "Save and next" },
      { key: "billModal.saveAndStay", cs: "Uložit a zůstat", en: "Save and stay" },
      { key: "billModal.aiReprocess", cs: "Zpracovat AI", en: "Process with AI" },
      { key: "billModal.aiReprocessSoon", cs: "Bude dostupné později", en: "Coming later" },
      { key: "nav.bills", cs: "Účtenky", en: "Bills" },
      { key: "nav.eventSetup", cs: "Nastavení akce", en: "Event setup" },
      { key: "billsPage.selectedCount", cs: "Vybráno: {count}", en: "Selected: {count}" },
      { key: "billsPage.bulkApprove", cs: "Schválit vybrané", en: "Approve selected" },
      { key: "billsPage.bulkDelete", cs: "Smazat vybrané", en: "Delete selected" },
      { key: "billsPage.clearSelection", cs: "Zrušit výběr", en: "Clear selection" },
      { key: "billsPage.confirmBulkDelete", cs: "Opravdu smazat {count} účtenek? Tuto akci nelze vrátit.", en: "Really delete {count} bills? This cannot be undone." },
      { key: "billsPage.bulkResult", cs: "Hotovo: {succeeded} · nezdařilo se: {failed}", en: "Done: {succeeded} · failed: {failed}" },
      { key: "billsPage.bulkFailed", cs: "Hromadná akce se nezdařila.", en: "Bulk action failed." },
      { key: "billsPage.bulkFailuresTitle", cs: "Nezpracované účtenky:", en: "Bills not processed:" },
      { key: "billsPage.bulkErrMissing", cs: "{filename} — chybí: {fields}", en: "{filename} — missing: {fields}" },
      { key: "billsPage.bulkErrSplit", cs: "{filename} — součet kategorií {splitTotal} ≠ částka {billTotal}", en: "{filename} — split {splitTotal} does not match total {billTotal}" },
      { key: "billsPage.bulkErrApproved", cs: "{filename} — již schváleno", en: "{filename} — already approved" },
      { key: "imageEditor.openButton", cs: "Upravit obrázek", en: "Edit image" },
      { key: "imageEditor.title", cs: "Úprava obrázku", en: "Edit image" },
      { key: "imageEditor.cropHint", cs: "Táhnutím myší vyberte oblast pro oříznutí (volitelné).", en: "Drag to select a crop area (optional)." },
      { key: "imageEditor.blackWhite", cs: "Černobíle", en: "Black and white" },
      { key: "imageEditor.contrast", cs: "Kontrast", en: "Contrast" },
      { key: "imageEditor.brightness", cs: "Jas", en: "Brightness" },
      { key: "imageEditor.apply", cs: "Uložit úpravy", en: "Save changes" },
      { key: "imageEditor.reset", cs: "Zrušit úpravy", en: "Reset" },
      { key: "imageEditor.revert", cs: "Obnovit původní", en: "Restore original" },
      { key: "imageEditor.confirmRevert", cs: "Obnovit původní naskenovaný obrázek a zahodit úpravy?", en: "Restore the original scan and discard edits?" },
      { key: "imageEditor.errorCanvas", cs: "Nepodařilo se připravit obrázek.", en: "Could not prepare the image." },
      { key: "imageEditor.errorExport", cs: "Nepodařilo se vytvořit upravený obrázek.", en: "Could not create the edited image." },
      { key: "imageEditor.errorRevert", cs: "Obnovení se nezdařilo.", en: "Restore failed." },
      { key: "imageEditor.error.duplicate_after_edit", cs: "Upravený obrázek je shodný s jinou účtenkou v této akci.", en: "The edited image matches another bill in this event." },
      { key: "imageEditor.error.pdf_not_editable", cs: "PDF soubory zatím nelze upravovat.", en: "PDF files cannot be edited yet." },
      { key: "imageEditor.error.bill_approved_locked", cs: "Schválenou účtenku nelze upravit.", en: "An approved bill cannot be edited." },
      { key: "imageEditor.error.event_closed_locked", cs: "Akce je uzavřená.", en: "The event is closed." },
      { key: "imageEditor.error.no_original", cs: "Původní obrázek není k dispozici.", en: "No original image available." },
      { key: "imageEditor.cornerHint", cs: "Přetáhněte čtyři rohy na okraje účtenky. Obrázek se narovná do obdélníku.", en: "Drag the four corners onto the edges of the receipt. The image will be straightened into a rectangle." },
      { key: "imageEditor.processing", cs: "Zpracovávám obrázek...", en: "Processing image..." },
      { key: "billsPage.noRate", cs: "kurz není k dispozici", en: "no rate available" },
      { key: "billsPage.totalExcludes", cs: "nezahrnuje {count} účtenek bez kurzu", en: "excludes {count} bills without a rate" },
      { key: "billModal.czkEquivalent", cs: "= {amount} Kč (kurz {rate} ze dne {date})", en: "= {amount} CZK (rate {rate} from {date})" },
      { key: "billModal.czkUnavailable", cs: "Přepočet na Kč není možný — chybí datum účtenky nebo kurz.", en: "CZK conversion unavailable — missing bill date or exchange rate." },
      { key: "billModal.error.missingFields.amountCzk", cs: "přepočet na Kč", en: "CZK amount" },
      { key: "nav.exchangeRates", cs: "Kurzy", en: "Exchange rates" },
      { key: "rates.title", cs: "Kurzy ČNB", en: "CNB exchange rates" },
      { key: "rates.subtitle", cs: "Denní kurzy devizového trhu. Aktualizují se automaticky v pracovní dny odpoledne.", en: "Daily central bank fixing rates. Updated automatically on weekday afternoons." },
      { key: "rates.fetchToday", cs: "Načíst dnešní kurz", en: "Fetch today rate" },
      { key: "rates.fetchTodayHint", cs: "ČNB vyhlašuje kurzy v pracovní dny kolem 14:30.", en: "CNB publishes rates on business days around 14:30." },
      { key: "rates.fetchDate", cs: "Načíst pro datum", en: "Fetch for date" },
      { key: "rates.backfill", cs: "Doplnit historii", en: "Backfill history" },
      { key: "rates.backfillHint", cs: "Počet dní zpět (max 60).", en: "Days back (max 60)." },
      { key: "rates.syncDone", cs: "Kurzy načteny pro {date}.", en: "Rates loaded for {date}." },
      { key: "rates.backfillDone", cs: "Doplněno {count} obchodních dní.", en: "Backfilled {count} business days." },
      { key: "rates.syncFailed", cs: "Načtení kurzů selhalo: {error}", en: "Loading rates failed: {error}" },
      { key: "rates.recalcTitle", cs: "Dopočet účtenek", en: "Recalculate bills" },
      { key: "rates.recalcPending", cs: "{count} účtenek čeká na přepočet do Kč.", en: "{count} bills are waiting for CZK conversion." },
      { key: "rates.recalcNone", cs: "Všechny účtenky mají přepočet do Kč.", en: "All bills have a CZK amount." },
      { key: "rates.recalcButton", cs: "Přepočítat účtenky", en: "Recalculate bills" },
      { key: "rates.recalcNote", cs: "Schválené účtenky se nikdy nepřepočítávají — jejich kurz zůstává zachován.", en: "Approved bills are never recalculated — their stored rate is preserved." },
      { key: "rates.recalcDone", cs: "Přepočítáno: {converted}, stále bez kurzu: {stillMissing}", en: "Converted: {converted}, still without a rate: {stillMissing}" },
      { key: "rates.recalcFailed", cs: "Přepočet selhal.", en: "Recalculation failed." },
      { key: "rates.tableTitle", cs: "Uložené kurzy", en: "Stored rates" },
      { key: "rates.colDate", cs: "Datum", en: "Date" },
      { key: "rates.empty", cs: "Zatím žádné kurzy.", en: "No rates yet." },
      { key: "driveSettings.title", cs: "Napojení na Google Drive", en: "Google Drive integration" },
      { key: "driveSettings.serviceAccountLabel", cs: "Servisní účet", en: "Service account" },
      { key: "driveSettings.instructionsIntro", cs: "Aby aplikace mohla číst a zapisovat soubory, nasdílejte příslušné složky na Google Drive s tímto servisním účtem:", en: "For the app to read and write files, share the relevant Drive folders with this service account:" },
      { key: "driveSettings.instructionsSteps", cs: "1. Otevřete složku na Google Drive.\n2. Klikněte pravým tlačítkem na složku a vyberte Sdílet.\n3. Vložte e-mail servisního účtu výše a nastavte roli Editor.", en: "1. Open the folder in Google Drive.\n2. Right-click the folder and choose Share.\n3. Paste the service account email above and set the role to Editor." },
      { key: "driveSettings.ingestFolderLabel", cs: "ID složky pro import účtenek", en: "Bill ingest folder ID" },
      { key: "driveSettings.exportFolderLabel", cs: "ID složky pro export", en: "Export folder ID" },
      { key: "driveSettings.folderIdHint", cs: "ID najdete v adrese složky na Google Drive, za /folders/.", en: "Find it in the folder's Drive URL, after /folders/." },
      { key: "driveSettings.saveFolders", cs: "Uložit složky", en: "Save folders" },
      { key: "driveSettings.errorSaveFailed", cs: "Nepodařilo se uložit nastavení Drive.", en: "Failed to save Drive settings." },
      { key: "driveSettings.testConnection", cs: "Otestovat připojení", en: "Test connection" },
      { key: "driveSettings.testing", cs: "Testuji...", en: "Testing..." },
      { key: "driveSettings.testResultAccessible", cs: "Přístup funguje ({name})", en: "Access works ({name})" },
      { key: "driveSettings.testResultIngestLabel", cs: "Import:", en: "Ingest:" },
      { key: "driveSettings.testResultExportLabel", cs: "Export:", en: "Export:" },
      { key: "driveSettings.noFoldersSet", cs: "Nejdřív vyplňte a uložte alespoň jedno ID složky.", en: "Fill in and save at least one folder ID first." },
      { key: "driveSettings.error.wrong_type", cs: "ID nepatří složce (jiný typ souboru).", en: "ID does not point to a folder (different file type)." },
      { key: "driveSettings.error.not_found", cs: "Složka nenalezena — zkontrolujte ID.", en: "Folder not found — check the ID." },
      { key: "driveSettings.error.access_denied", cs: "Přístup odepřen — složka není nasdílená se servisním účtem.", en: "Access denied — the folder is not shared with the service account." },
      { key: "driveSettings.error.unknown", cs: "Neznámá chyba při ověřování přístupu.", en: "Unknown error while checking access." },
      { key: "driveSettings.importButton", cs: "Importovat nyní", en: "Import now" },
      { key: "driveSettings.importing", cs: "Importuji...", en: "Importing..." },
      { key: "driveSettings.importNoFolderSet", cs: "Nejdřív nastavte a uložte složku pro import.", en: "Set and save the ingest folder first." },
      { key: "driveSettings.importResultSummary", cs: "Vytvořeno: {created}, duplicity: {duplicates}", en: "Created: {created}, duplicates: {duplicates}" },
      { key: "driveSettings.importAuthorsSummary", cs: "Autoři: {matched} spárováno, {created} nově vytvořeno", en: "Authors: {matched} matched, {created} newly created" },
      { key: "driveSettings.importSkippedAlready", cs: "Přeskočeno (již dříve importováno): {count}", en: "Skipped (already imported before): {count}" },
      { key: "driveSettings.importSkippedNativeTitle", cs: "Přeskočené soubory Google (nelze importovat jako účtenku):", en: "Skipped Google files (cannot be imported as a bill):" },
      { key: "driveSettings.importSkippedNativeItem", cs: "{filename} (složka {subfolderName})", en: "{filename} (folder {subfolderName})" },
      { key: "driveSettings.error.event_closed_locked", cs: "Akce je uzavřená, import není možný.", en: "The event is closed, import is not possible." },
      { key: "driveSettings.error.no_ingest_folder", cs: "Nejdřív nastavte a uložte složku pro import.", en: "Set and save the ingest folder first." },
      { key: "driveSettings.error.event_not_found", cs: "Akce nenalezena.", en: "Event not found." },
      { key: "driveSettings.error.generic", cs: "Import se nezdařil.", en: "Import failed." },
      { key: "driveSettings.exportButton", cs: "Exportovat do Drive", en: "Export to Drive" },
      { key: "driveSettings.exporting", cs: "Exportuji...", en: "Exporting..." },
      { key: "driveSettings.exportNoFolderSet", cs: "Nejdřív nastavte a uložte složku pro export.", en: "Set and save the export folder first." },
      { key: "driveSettings.exportResultSummary", cs: "Schváleno: {total}, nově exportováno: {new}, již exportováno: {already}", en: "Approved: {total}, newly exported: {new}, already exported: {already}" },
      { key: "driveSettings.exportOpenManifest", cs: "Otevřít manifest", en: "Open manifest" },
      { key: "driveSettings.error.no_export_folder", cs: "Nejdřív nastavte a uložte složku pro export.", en: "Set and save the export folder first." },
      { key: "driveSettings.error.no_approved_bills", cs: "Žádné schválené účtenky k exportu.", en: "No approved bills to export." },
      { key: "driveSettings.error.exportGeneric", cs: "Export se nezdařil.", en: "Export failed." },
      { key: "eventDetail.viewBudgetLink", cs: "Čerpání rozpočtu", en: "Budget Spending" },
      { key: "budgetPage.title", cs: "Čerpání rozpočtu", en: "Budget Spending" },
      { key: "budgetPage.colActual", cs: "Skutečnost (Kč)", en: "Actual (CZK)" },
      { key: "budgetPage.colRemaining", cs: "Zbývá (Kč)", en: "Remaining (CZK)" },
      { key: "eventDetail.viewPaymentsLink", cs: "Platby", en: "Payments" },
      { key: "paymentsPage.title", cs: "Platby", en: "Payments" },
      { key: "paymentsPage.colBillCount", cs: "počet účtenek", en: "bill count" },
      { key: "paymentsPage.noBankDetails", cs: "Chybí bankovní údaje", en: "Missing bank details" },
      { key: "paymentsPage.editBankButton", cs: "Upravit bankovní údaje", en: "Edit bank details" },
      { key: "paymentsPage.markPaidButton", cs: "Označit jako proplaceno", en: "Mark as paid" },
      { key: "paymentsPage.markPaidConfirm", cs: "Opravdu označit {count} účtenek autora {name} jako proplacené?", en: "Really mark {count} bills for {name} as paid?" },
      { key: "paymentsPage.markPaidFailed", cs: "Označení se nezdařilo.", en: "Failed to mark as paid." },
      { key: "paymentsPage.empty", cs: "Žádné nezaplacené účtenky.", en: "No unpaid bills." },
      { key: "paymentsPage.qrUnavailable", cs: "QR kód nelze vygenerovat — zkontrolujte bankovní údaje.", en: "QR code unavailable — check bank details." },
      { key: "paymentsPage.ibanLabel", cs: "IBAN", en: "IBAN" },
      { key: "billModal.unmarkPaidButton", cs: "Zrušit proplacení", en: "Unmark as paid" },
      { key: "billModal.paidStatusPaid", cs: "Proplaceno {date}", en: "Paid {date}" },
      { key: "billModal.paidStatusUnpaid", cs: "Neproplaceno", en: "Not paid" },
      { key: "billModal.error.no_payer", cs: "Nelze označit — účtenka nemá autora k proplacení.", en: "Cannot mark as paid — no payer set for this bill." },
      { key: "billModal.error.not_approved", cs: "Nelze označit jako proplaceno — účtenka není schválená.", en: "Cannot mark as paid — bill is not approved." },
      { key: "billModal.error.unmarkPaidFailed", cs: "Zrušení proplacení se nezdařilo.", en: "Failed to unmark as paid." },
      { key: "nav.health", cs: "Zdraví", en: "Health" },
      { key: "eventSettings.tabSettings", cs: "Kategorie", en: "Categories" },
      { key: "eventSettings.tabDrive", cs: "Google Drive", en: "Google Drive" },
      { key: "eventSettings.tabAccess", cs: "Přístup", en: "Access" },
      { key: "eventSettings.tabModules", cs: "Moduly", en: "Modules" },
      { key: "accessTab.modulesTitle", cs: "Moduly", en: "Modules" },
      { key: "accessTab.moduleBills", cs: "Účtenky", en: "Bills" },
      { key: "accessTab.moduleHealth", cs: "Zdraví", en: "Health" },
      { key: "accessTab.moduleEnabledHint", cs: "Zapnuto pro tuto akci", en: "Enabled for this event" },
      { key: "accessTab.usersTitle", cs: "Přístup uživatelů", en: "User access" },
      { key: "accessTab.colUser", cs: "Uživatel", en: "User" },
      { key: "accessTab.shortcutAdmin", cs: "administrátor — vždy má přístup", en: "admin — always has access" },
      { key: "accessTab.shortcutAccountant", cs: "účetní — vždy má přístup k účtenkám", en: "accountant — always has access to Bills" },
      { key: "accessTab.errorLoadFailed", cs: "Nepodařilo se načíst přístupy.", en: "Failed to load access settings." },
      { key: "accessTab.errorSaveFailed", cs: "Nepodařilo se uložit změnu.", en: "Failed to save the change." },
      { key: "participantsPage.title", cs: "Účastníci", en: "Participants" },
      { key: "participantsPage.searchPlaceholder", cs: "Hledat podle jména…", en: "Search by name…" },
      { key: "participantsPage.searchNoMatches", cs: "Žádný účastník neodpovídá hledání.", en: "No participant matches your search." },
      { key: "participantsPage.empty", cs: "Zatím žádní účastníci.", en: "No participants yet." },
      { key: "participantsPage.addButton", cs: "+ Přidat účastníka", en: "+ Add participant" },
      { key: "participantsPage.colGroup", cs: "Skupina", en: "Group" },
      { key: "participantsPage.errorAddFailed", cs: "Nepodařilo se přidat účastníka.", en: "Failed to add participant." },
      { key: "participantDetail.notesTitle", cs: "Zdravotní poznámky", en: "Health notes" },
      { key: "participantDetail.notesEmpty", cs: "Bez zdravotních poznámek.", en: "No health notes." },
      { key: "participantDetail.allergiesLabel", cs: "Alergie", en: "Allergies" },
      { key: "participantDetail.medsNotesLabel", cs: "Poznámky k lékům", en: "Medication notes" },
      { key: "participantDetail.chronicIssuesLabel", cs: "Chronické potíže", en: "Chronic issues" },
      { key: "participantDetail.otherNotesLabel", cs: "Ostatní poznámky", en: "Other notes" },
      { key: "participantDetail.guardiansTitle", cs: "Zákonní zástupci", en: "Guardians" },
      { key: "participantDetail.guardiansEmpty", cs: "Zatím žádní zákonní zástupci.", en: "No guardians yet." },
      { key: "participantDetail.addGuardianButton", cs: "+ Přidat zástupce", en: "+ Add guardian" },
      { key: "participantDetail.guardianEmailLabel", cs: "E-mail", en: "Email" },
      { key: "participantDetail.guardianRelationshipLabel", cs: "Vztah (matka, otec, …)", en: "Relationship" },
      { key: "participantDetail.receivesCommunicationsLabel", cs: "Dostává e-maily", en: "Receives emails" },
      { key: "participantDetail.confirmRemoveGuardian", cs: "Opravdu odebrat tohoto zástupce?", en: "Really remove this guardian?" },
      { key: "participantDetail.errorSaveFailed", cs: "Nepodařilo se uložit změny.", en: "Failed to save changes." },
      { key: "participantDetail.confirmDeleteParticipant", cs: "Opravdu smazat účastníka „{name}“? Smažou se i jeho záznamy a plány léků.", en: "Really delete \"{name}\"? Their records and med plans will be deleted too." },
      { key: "participantDetail.errorDeleteFailed", cs: "Smazání se nezdařilo.", en: "Failed to delete." },
      { key: "participantsPage.importButton", cs: "Importovat účastníky", en: "Import participants" },
      { key: "participantImportPage.title", cs: "Import účastníků", en: "Import participants" },
      { key: "participantImportPage.instructions", cs: "Vyberte a zkopírujte rozsah buněk v Google Sheets (včetně záhlaví) a vložte jej sem.", en: "Select and copy a range of cells in Google Sheets (including the header row) and paste it here." },
      { key: "participantImportPage.pastePlaceholder", cs: "Vložte data zkopírovaná z tabulky…", en: "Paste data copied from a spreadsheet…" },
      { key: "participantImportPage.mappingTitle", cs: "Mapování sloupců", en: "Column mapping" },
      { key: "participantImportPage.field.ignore", cs: "Ignorovat", en: "Ignore" },
      { key: "participantImportPage.field.name", cs: "Jméno", en: "Name" },
      { key: "participantImportPage.field.groupName", cs: "Skupina", en: "Group" },
      { key: "participantImportPage.field.allergies", cs: "Alergie", en: "Allergies" },
      { key: "participantImportPage.field.medsNotes", cs: "Poznámky k lékům", en: "Medication notes" },
      { key: "participantImportPage.field.chronicIssues", cs: "Chronické potíže", en: "Chronic issues" },
      { key: "participantImportPage.field.otherNotes", cs: "Ostatní poznámky", en: "Other notes" },
      { key: "participantImportPage.field.guardianEmail", cs: "E-mail zákonného zástupce", en: "Guardian email" },
      { key: "participantImportPage.field.dateOfBirth", cs: "Datum narození", en: "Date of birth" },
      { key: "participantImportPage.field.guardianName", cs: "Jméno zákonného zástupce", en: "Guardian name" },
      { key: "participantImportPage.previewSummary", cs: "{valid} v pořádku, {invalid} s chybou", en: "{valid} ok, {invalid} with errors" },
      { key: "participantImportPage.colStatus", cs: "Stav", en: "Status" },
      { key: "participantImportPage.statusOk", cs: "OK", en: "OK" },
      { key: "participantImportPage.error.missing_name", cs: "chybí jméno", en: "missing name" },
      { key: "participantImportPage.error.invalid_email", cs: "neplatný e-mail", en: "invalid email" },
      { key: "participantImportPage.importButton", cs: "Importovat", en: "Import" },
      { key: "participantImportPage.doneMessage", cs: "Importováno {count} účastníků.", en: "Imported {count} participants." },
      { key: "participantImportPage.doneFailures", cs: "{count} se nepodařilo importovat.", en: "{count} failed to import." },
      { key: "participantImportPage.goToParticipants", cs: "Zpět na účastníky", en: "Back to participants" },
      { key: "participantImportPage.duplicatesFound", cs: "{count} možných duplicit.", en: "{count} possible duplicates." },
      { key: "participantImportPage.duplicateOf", cs: "Už existuje (skupina: {group})", en: "Already exists (group: {group})" },
      { key: "participantImportPage.actionSkip", cs: "Přeskočit", en: "Skip" },
      { key: "participantImportPage.actionMerge", cs: "Sloučit", en: "Merge" },
      { key: "participantImportPage.actionCreateAnyway", cs: "Přesto vytvořit", en: "Create anyway" },
      { key: "participantImportPage.doneMerged", cs: "Sloučeno {count}.", en: "Merged {count}." },
      { key: "participantImportPage.doneSkipped", cs: "Přeskočeno {count}.", en: "Skipped {count}." },
      { key: "participantImportPage.bulkActionLabel", cs: "U všech duplicit:", en: "For all duplicates:" },
      { key: "participantImportPage.bulkActionPlaceholder", cs: "Nastavit akci pro všechny…", en: "Set action for all…" },
      { key: "incidentsPage.title", cs: "Záznamy", en: "Records" },
      { key: "incidentsPage.empty", cs: "Zatím žádné záznamy.", en: "No records yet." },
      { key: "incidentsPage.addButton", cs: "+ Záznam", en: "+ Record" },
      { key: "incidentsPage.detailButton", cs: "Detail", en: "Detail" },
      { key: "incidentsPage.followUpButton", cs: "+ Follow-up", en: "+ Follow-up" },
      { key: "incidentsPage.showFollowUps", cs: "Zobrazit follow-upy ({count})", en: "Show follow-ups ({count})" },
      { key: "incidentsPage.hideFollowUps", cs: "Skrýt follow-upy", en: "Hide follow-ups" },
      { key: "incidentForm.titleNew", cs: "Nový záznam", en: "New record" },
      { key: "incidentForm.titleEdit", cs: "Upravit záznam", en: "Edit record" },
      { key: "incidentForm.titleFollowUp", cs: "Follow-up", en: "Follow-up" },
      { key: "incidentForm.followUpLockedNote", cs: "Follow-up ke stejné situaci — kategorie a umístění na těle jsou převzaty ({category}).", en: "Follow-up on the same situation — category and body location are inherited ({category})." },
      { key: "incidentForm.category.illness", cs: "Nemoc", en: "Illness" },
      { key: "incidentForm.category.injury", cs: "Úraz", en: "Injury" },
      { key: "incidentForm.category.parasite", cs: "Parazit", en: "Parasite" },
      { key: "incidentForm.category.medication", cs: "Medikace", en: "Medication" },
      { key: "incidentForm.category.other", cs: "Ostatní", en: "Other" },
      { key: "incidentForm.summaryLabel", cs: "Shrnutí", en: "Summary" },
      { key: "incidentForm.tempLabel", cs: "Teplota (°C)", en: "Temperature (°C)" },
      { key: "incidentForm.medLabel", cs: "Lék", en: "Medication" },
      { key: "incidentForm.medOther", cs: "jiné…", en: "other…" },
      { key: "incidentForm.detailsLabel", cs: "Podrobnosti", en: "Details" },
      { key: "incidentForm.photoLabel", cs: "Fotka", en: "Photo" },
      { key: "incidentForm.choosePhoto", cs: "Vybrat soubor", en: "Choose file" },
      { key: "incidentForm.takePhoto", cs: "Vyfotit", en: "Take photo" },
      { key: "incidentForm.saveFollowUp", cs: "Uložit follow-up", en: "Save follow-up" },
      { key: "incidentForm.errorPhotoFailed", cs: "Nepodařilo se nahrát fotku.", en: "Failed to upload photo." },
      { key: "incidentForm.errorSaveFailed", cs: "Nepodařilo se uložit záznam.", en: "Failed to save the record." },
      { key: "incidentDetail.editButton", cs: "Upravit", en: "Edit" },
      { key: "incidentDetail.followUpButton", cs: "+ Follow-up", en: "+ Follow-up" },
      { key: "incidentDetail.deleteButton", cs: "Smazat", en: "Delete" },
      { key: "incidentDetail.confirmDelete", cs: "Opravdu smazat tento záznam?", en: "Really delete this record?" },
      { key: "bodyMap.title", cs: "Umístění na těle", en: "Body location" },
      { key: "bodyMap.front", cs: "Přední", en: "Front" },
      { key: "bodyMap.back", cs: "Zadní", en: "Back" },
      { key: "participantsPage.colAge", cs: "Věk", en: "Age" },
      { key: "participantsPage.dobLabel", cs: "Datum narození", en: "Date of birth" },
      { key: "participantsPage.addIncidentButton", cs: "+ Záznam", en: "+ Record" },
      { key: "participantsPage.selectedCount", cs: "Vybráno: {count}", en: "Selected: {count}" },
      { key: "participantsPage.bulkDeleteButton", cs: "Smazat vybrané", en: "Delete selected" },
      { key: "participantsPage.confirmBulkDelete", cs: "Opravdu smazat {count} účastníků? Smažou se i jejich záznamy a plány léků. Tuto akci nelze vrátit.", en: "Really delete {count} participants? Their records and med plans will be deleted too. This cannot be undone." },
      { key: "participantsPage.bulkResult", cs: "Hotovo: {succeeded} · nezdařilo se: {failed}", en: "Done: {succeeded} · failed: {failed}" },
      { key: "participantsPage.bulkFailed", cs: "Hromadná akce se nezdařila.", en: "Bulk action failed." },
      { key: "incidentForm.showParticipantSummary", cs: "Zobrazit podrobnosti…", en: "Show details…" },
      { key: "incidentForm.hideParticipantSummary", cs: "Skrýt podrobnosti", en: "Hide details" },
      { key: "nav.healthTemplates", cs: "Šablony zdraví", en: "Health templates" },
      { key: "nav.templates", cs: "Šablony", en: "Templates" },
      { key: "templatesPage.tabHealth", cs: "Zdraví", en: "Health" },
      { key: "templatesPage.tabBills", cs: "Účtenky", en: "Bills" },
      { key: "eventSettings.tabHealth", cs: "Zdraví", en: "Health" },
      { key: "eventHealthTab.slotsLabel", cs: "Časy podání", en: "Time slots" },
      { key: "healthTemplatesPage.title", cs: "Šablony zdraví", en: "Health templates" },
      { key: "healthTemplatesPage.subtitle", cs: "Výchozí seznamy léků a situací pro nové akce.", en: "Default med and situation lists for new events." },
      { key: "healthTemplatesPage.tabMeds", cs: "Léky", en: "Meds" },
      { key: "healthTemplatesPage.tabSituations", cs: "Situace", en: "Situations" },
      { key: "listTemplateAdmin.empty", cs: "Zatím nic.", en: "Nothing yet." },
      { key: "listTemplateAdmin.deactivate", cs: "Deaktivovat", en: "Deactivate" },
      { key: "listTemplateAdmin.activate", cs: "Aktivovat", en: "Activate" },
      { key: "listTemplateAdmin.errorSaveFailed", cs: "Nepodařilo se uložit.", en: "Failed to save." },
      { key: "listTemplateAdmin.syncFromTemplates", cs: "Načíst ze šablon", en: "Load from templates" },
      { key: "listTemplateAdmin.errorSyncFailed", cs: "Nepodařilo se načíst šablony.", en: "Failed to load templates." },
      { key: "listTemplateAdmin.confirmDelete", cs: "Opravdu smazat „{name}“?", en: "Really delete \"{name}\"?" },
      { key: "listTemplateAdmin.errorItemInUse", cs: "Nelze smazat — položka je použita u účastníka.", en: "Can't delete — item is in use by a participant." },
      { key: "listTemplateAdmin.errorDeleteFailed", cs: "Smazání se nezdařilo.", en: "Failed to delete." },
      { key: "listTemplateAdmin.shortDescriptionLabel", cs: "Krátký popis", en: "Short description" },
      { key: "medPlansSection.title", cs: "Léky", en: "Meds" },
      { key: "medPlansSection.addButton", cs: "+ Přidat lék", en: "+ Add medication" },
      { key: "medPlansSection.selectMed", cs: "Vyberte lék", en: "Select medication" },
      { key: "medPlansSection.selectSlot", cs: "Vyberte čas", en: "Select time" },
      { key: "medPlansSection.doseLabel", cs: "Dávka", en: "Dose" },
      { key: "medPlansSection.empty", cs: "Zatím žádné léky.", en: "No medications yet." },
      { key: "medPlansSection.confirmRemove", cs: "Opravdu odebrat tento lék?", en: "Really remove this medication?" },
      { key: "medChecklistPage.title", cs: "Výdej léků", en: "Med checklist" },
      { key: "medChecklistPage.progress", cs: "Podáno {given} z {total}", en: "Given {given} of {total}" },
      { key: "medChecklistPage.empty", cs: "Pro tento čas nejsou naplánované žádné léky.", en: "No meds scheduled for this time." },
      { key: "medGridPage.title", cs: "Přehled léků", en: "Meds overview" },
      { key: "medGridPage.preset.today", cs: "Dnes", en: "Today" },
      { key: "medGridPage.preset.week", cs: "Tento týden", en: "This week" },
      { key: "medGridPage.preset.event", cs: "Celá akce", en: "Whole event" },
      { key: "medGridPage.preset.custom", cs: "Vlastní rozsah", en: "Custom range" },
      { key: "medGridPage.expandHint", cs: "Klikněte na den pro zobrazení jednotlivých časů.", en: "Click a day to show its individual time slots." },
      { key: "pdfExport.modeBlank", cs: "Prázdný (k vyplnění)", en: "Blank (to fill in)" },
      { key: "pdfExport.modeHybrid", cs: "Aktuální stav", en: "Current status" },
      { key: "pdfExport.downloadButton", cs: "Stáhnout PDF", en: "Download PDF" },
      { key: "nav.translations", cs: "Překlady", en: "Translations" },
      { key: "translationsPage.searchPlaceholder", cs: "Hledat podle klíče nebo textu...", en: "Search by key or text..." },
      { key: "translationsPage.colKey", cs: "Klíč", en: "Key" },
      { key: "translationsPage.colUsedIn", cs: "Použito v", en: "Used in" },
      { key: "translationsPage.empty", cs: "Žádné překlady neodpovídají hledání.", en: "No translations match your search." },
      { key: "translationsPage.errorSaveFailed", cs: "Uložení se nezdařilo.", en: "Failed to save." },
      { key: "common.close", cs: "Zavřít", en: "Close" },
      { key: "healthTemplatesPage.tabEmail", cs: "E-mail", en: "Email" },
      { key: "emailTemplateAdmin.errorLoadFailed", cs: "Načtení šablony se nezdařilo.", en: "Failed to load the template." },
      { key: "emailTemplateAdmin.errorSaveFailed", cs: "Uložení se nezdařilo.", en: "Failed to save." },
      { key: "emailTemplateAdmin.revertToDefault", cs: "Vrátit na výchozí", en: "Revert to default" },
      { key: "emailTemplateAdmin.usingOrgDefault", cs: "Používá se výchozí šablona organizace.", en: "Using the organization's default template." },
      { key: "emailTemplateAdmin.subjectLabel", cs: "Předmět", en: "Subject" },
      { key: "emailTemplateAdmin.bodyLabel", cs: "Text zprávy", en: "Body" },
      { key: "emailTemplateAdmin.previewTitle", cs: "Náhled", en: "Preview" },
      { key: "participantDetail.downloadPdfButton", cs: "Stáhnout PDF", en: "Download PDF" },
      { key: "sendSummary.sendButtonShort", cs: "Odeslat souhrn rodičům", en: "Send summary to guardians" },
      { key: "sendSummary.title", cs: "Odeslat souhrn rodičům", en: "Send summary to guardians" },
      { key: "sendSummary.errorLoadFailed", cs: "Načtení náhledu se nezdařilo.", en: "Failed to load the preview." },
      { key: "sendSummary.errorSendFailed", cs: "Odeslání se nezdařilo.", en: "Sending failed." },
      { key: "sendSummary.noRecipients", cs: "Žádný zákonný zástupce nemá povolen příjem zpráv.", en: "No guardian has communications enabled." },
      { key: "sendSummary.recipientsLabel", cs: "Příjemci", en: "Recipients" },
      { key: "sendSummary.subjectLabel", cs: "Předmět", en: "Subject" },
      { key: "sendSummary.sendButton", cs: "Odeslat", en: "Send" },
      { key: "sendSummary.resultMessage", cs: "Odesláno: {sent} · nezdařilo se: {failed}", en: "Sent: {sent} · failed: {failed}" },
      { key: "sendLog.title", cs: "Odeslané e-maily", en: "Sent emails" },
      { key: "sendLog.empty", cs: "Zatím žádné odeslané e-maily.", en: "No emails sent yet." },
      { key: "sendLog.colGuardian", cs: "Zákonný zástupce", en: "Guardian" },
      { key: "sendLog.colSentAt", cs: "Odesláno", en: "Sent at" },
      { key: "sendLog.colStatus", cs: "Stav", en: "Status" },
      { key: "sendLog.statusSent", cs: "Odesláno", en: "Sent" },
      { key: "sendLog.statusFailed", cs: "Nezdařilo se", en: "Failed" },
      { key: "sendLog.resendButton", cs: "Odeslat znovu", en: "Resend" },
      { key: "bulkSendSummaries.entryPoint", cs: "Odeslat souhrny všem rodičům", en: "Send summaries to all guardians" },
      { key: "bulkSendSummaries.title", cs: "Odeslat souhrny všem rodičům", en: "Send summaries to all guardians" },
      { key: "bulkSendSummaries.tabSend", cs: "Odeslat", en: "Send" },
      { key: "bulkSendSummaries.selectAll", cs: "Vybrat vše", en: "Select all" },
      { key: "bulkSendSummaries.confirm", cs: "Opravdu odeslat souhrn {count} rodičům? Tato akce se nedá vzít zpět.", en: "Really send the summary to {count} guardians? This cannot be undone." },
      { key: "bulkSendSummaries.sendButton", cs: "Odeslat ({count})", en: "Send ({count})" },
      { key: "bulkSendSummaries.resultInline", cs: "odesláno: {sent} · nezdařilo se: {failed}", en: "sent: {sent} · failed: {failed}" },
    ],
    skipDuplicates: true,
  });

  // ListTemplate has no natural unique key to dedupe createMany against, so
  // seed these idempotently by checking first.
  const defaultSlots = [
    { name: "ráno", sortOrder: 1 },
    { name: "po obědě", sortOrder: 2 },
    { name: "po večeři", sortOrder: 3 },
    { name: "před spaním", sortOrder: 4 },
  ];
  for (const slot of defaultSlots) {
    const existing = await prisma.listTemplate.findFirst({
      where: { kind: "slot", name: slot.name },
    });
    if (!existing) {
      await prisma.listTemplate.create({
        data: { kind: "slot", name: slot.name, sortOrder: slot.sortOrder },
      });
    }
  }
}

main().finally(() => prisma.$disconnect());
